### ISSUE TITLE
rendering of code snippet

### ISSUE THREAD

**Issue by sebgoa** [rtfd/sphinx_rtd_theme#104]
Hi, when using the code directive for bash commands, the rendering is different if we prepend the command by # or $. The non root commands get rendered with courier font without a box and the root commands (#) get a box around them.

See http://apache-cloudstack-release-notes.readthedocs.org/en/latest/rnotes.html for an example.

I can't seem to find my way around it.

Any help appreciated

**Comment by Blendify** [comment]
Can you provide new example? The one in you comment gives a 404.

**Comment by sebgoa** [comment]
I am closing this, this was 3 years ago.
