### ISSUE TITLE
Low contrast text in footnotes strains legibility

### ISSUE THREAD

**Issue by SavinaRoja** [rtfd/sphinx_rtd_theme#110]
I am having a lot of trouble reading the text in my footnotes and would like to be able to use higher-contrast text in my RTD theme. Is there are recommended way to adjust this while keeping the standard theme, or could it be amended (perhaps as a configurable option if some prefer the current style) in the theme?

For reference (the footnote at the bottom):
http://openaccess-epub.readthedocs.org/en/latest/usageguide.html

**Comment by agjohnson** [comment]
I'm not sure this would be a meaningful configuration option, I would suggest overriding this with a css include. You can do this by extending the theme, adding css overrides under `_static`, and appending the files to `extra_css_files` in a `layout.html` override.

**Comment by Blendify** [comment]
I darkened the text ever so slightly `#999` to `#808080` like @agjohnson said you can also override the color in your own css.
