### ISSUE TITLE
Extra markup is added to unordered list items if there is a nested list

### ISSUE THREAD

**Issue by swill** [rtfd/sphinx_rtd_theme#119]
If you have the syntax:

```
- some
- text
- list
```

It renders correctly as:

```
- some
- text
- list
```

However, if you have nested lists inside, like this:

```
- some

   - nested
   - list

- text
- list
```

It should render like this:

```
- some
   - nested
   - list
- text
- list
```

Instead it renders like this:

```
- some

   - nested

   - list

- text

- list
```

It renders like this because there is extra markup added inside the list item.

The code should render to this:

```
<ul>
   <li>some
      <ul>
         <li>nested</li>
         <li>list</li>
      </ul>
   </li>
   <li>text</li>
   <li>list</li>
</ul>
```

But instead, it renders to this:

```
<ul>
   <li><p class="first">some</p>
      <blockquote><div><ul class="simple">
          <li>nested</li>
          <li>list</li>
      </ul></div></blockquote>
   </li>
   <li><p class="first">text</p></li>
   <li><p class="first">list</p></li>
</ul>
```

**Comment by jessetan** [comment]
Old issue, but looks to be a result of bad input; all list item content must be indented to same level as first character of list item

The provided example uses three spaces to indent the nested list:
```rst
- some

   - nested
   - list

- text
- list
```

Only two spaces are required to mark the indented list as the content of the first bullet of the outer list. The third space is [interpreted as a blockquote](http://docutils.sourceforge.net/docs/user/rst/quickref.html#block-quotes).
Correct rst source:
```rst
- some

  - nested
  - list

- text
- list
```
