### ISSUE TITLE
TOC visually indicate separate toctree's

### ISSUE THREAD

**Issue by pkra** [rtfd/sphinx_rtd_theme#120]
I was wondering what you think about implementing some visual cue in the table of contents that indicates the different `toctree`'s in `index.rst`. 

For example, on https://docs.readthedocs.org/, this would help differentiate the parts of the documentation (e.g. separating User Documentation from Features for rtd). I think this would help readers to parse a long table of contents.

**Comment by Blendify** [comment]
I am going to close this I do not think it is an issue anymore. If it is we can re-open this.
