### ISSUE TITLE
List items' font size doesn't match with paragraph font-size.

### ISSUE THREAD

**Issue by mindprince** [rtfd/sphinx_rtd_theme#125]
![sphinx_rtd_theme_font_size](https://cloud.githubusercontent.com/assets/695290/3219259/04e08382-eff4-11e3-9438-3d1fd83ca0c9.png)
As shown in the attached screenshot, the font-size for list items doesn't match the font size of the text everywhere else.

I may be wrong but I believe this is because I use a larger default font size in Chrome and for list items the theme doesn't override this font size.

**Comment by mkleehammer** [comment]
I am seeing the same thing with [pglib](http://pglib.readthedocs.io/en/latest/quick-start.html) - the bulleted lists do not have the same font size set.  Any news on this issue?

**Comment by twm** [comment]
To provide more detail:

* A rule for `p` sets `font-size: 16px` (which is the default in most desktop browsers).
* The font size for `li` is not set, so it assumes the browser's default font size (`font-size: 100%` is set on the `html` element).

There are two ways to fix the discrepancy:

* The expedient, wrong way: set `font-size: 16px` on the `html` element.
* The right way: change all rules which set font size in `px` to use a relative unit (`rem` is the easiest to use). This respects users' configured font size (and is also likely to improve display on devices with a base font size other than 16 pixels, like TVs and phones).

Unfortunately the second option may require a lot of change throughout the stylesheet if many things are specified in `px` which should really be relative to text size (e.g., the indentation of `<li>` appears to be set in `px`).

**Comment by psss** [comment]
I've run into this issue with numbered list today (also have 18 as the default):
http://did.readthedocs.io/en/latest/plugins/#module-did.plugins.google
I would suggest to remove the hard 16px size specification.

**Comment by jachiam** [comment]
I seem to be having this issue as well - has there been a fix for this in the 4+ years since it was raised, that I'm just missing?

**Comment by jessetan** [comment]
I've created a PR for the easy, but not ideal, fix. Changing all sizing and layout to use relative spacing is probably a lot of work. We can tackle that if we ever do a rewrite to ditch Wyrm, see #544
