### ISSUE TITLE
Google Analytics Integration for Users is broken

### ISSUE THREAD

**Issue by safl** [rtfd/sphinx_rtd_theme#130]
It seems that integration with Google Analytics is broken, the analytics for users that is.
This might be because the snippet from Google differs from that of the one used by RTD.

Analytics snippet:

``` javascript
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'xxxxxxxxxxx', 'auto');
  ga('send', 'pageview');
</script>
```

I have tried working around by customizing the theme.

``` javascript

{% extends "!layout.html" %}
{% block extrahead %}
{{ super() }}
<script>
  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-MYUA-CODE', 'auto');
  ga('send', 'pageview');
</script>
{% endblock %}
```

This works when building sphinxdocs locally but the theme-customization is not available when docs are built on readthedocs.org. I assume that is because readthedocs.org filter out such modifications to avoid users overwriting existing Google Analytics integration.

**Comment by Blendify** [comment]
I would recommend using https://pypi.python.org/pypi/sphinxcontrib-googleanalytics

Also, have a look at http://www.sphinx-doc.org/en/stable/faq.html This worked for me before moving to the above option. Anyway please close this.
