### ISSUE TITLE
Add ability to display global announcements using the default theme

### ISSUE THREAD

**Issue by guillermooo** [rtfd/sphinx_rtd_theme#131]
_(As discussed via IRC.)_

It'd be great to be able to enable large, prominent site-wide banners for important announcements. At the moment, it doesn't seem possible using the default theme.

**Comment by Blendify** [comment]
What about something like https://robpol86.github.io/sphinxcontrib-versioning/ or we can do something like readthedocs.

**Comment by Blendify** [comment]
@ericholscher @agjohnson

**Comment by ericholscher** [comment]
That enables versioning, not really an announcement thing? I'd be curious how to implement this, I'm not 100% sure it belongs in the theme. Do any of the other themes have this ability?

**Comment by Blendify** [comment]
> Do any of the other themes have this ability?

I do not think so

**Comment by Blendify** [comment]
> That enables versioning, not really an announcement thing?

Checkout the banner they have on the top of the page.

**Comment by ericholscher** [comment]
I believe that is just a `.. warning:` no?

**Comment by Blendify** [comment]
No, it is a custom `scv-banner scv-sphinx_rtd_theme` class

**Comment by agjohnson** [comment]
I don't think we need something specific for this use case, its rather limited. We could simply add a block for override in the template, similar to `extrabody`. Or, perhaps have some pattern for adding content to this block through config overrides.

**Comment by Blendify** [comment]
Closing as the general consensus is that this should not be a theme feature but implemented in an extension similar to the one I linked.
