### ISSUE TITLE
make_toctree() got an unexpected keyword argument 'includehidden'

### ISSUE THREAD

**Issue by ofqwx** [rtfd/sphinx_rtd_theme#138]
When I execute make html command, I receive this error "make_toctree() got an unexpected keyword argument 'includehidden'"

**Comment by eblur** [comment]
I had this same problem.  Before trying sphinx_rtd_theme, I had modified the Table of Contents behavior using the sphinxcontrib-fulltoc extension (https://sphinxcontrib-fulltoc.readthedocs.org/en/latest/install.html).

Once I removed this from my extensions list in conf.py, my files built just fine. So I would check if you're using extensions that modify the toctree behavior, which might conflict.

**Comment by Blendify** [comment]
Closing this, I doubt it is an issue in the theme and this is an old report.
