### ISSUE TITLE
Including GWT site verification metadata (and all/any metadata from source).

### ISSUE THREAD

**Issue by myroslav** [rtfd/sphinx_rtd_theme#157]
While including GWT site verification metadata in `index.rst` like:

```
  .. meta::
      :google-site-verification: some-site-code
```

I do see that in "stock" Sphinx theme as:

```
  <meta content="some-site-code" name="google-site-verification" />
```

but not in `sphinx_rtd_theme`. `basic` theme includes that as `{{ metatags }}` right after `meta http-equiv="Content-Type"`, should `sphinx_rtd_theme` include that as well?

**Comment by Blendify** [comment]
This has been fixed in c38702d9e7cab14efeeda615ea80e05a4cadb775
