### ISSUE TITLE
Error on grunt sass:dev task, invalid CSS

### ISSUE THREAD

**Issue by ricardodani** [rtfd/sphinx_rtd_theme#160]
Running "sass:dev" (sass) task
Syntax error: Invalid CSS after "      webkit-image": expected ")", was ": -webkit- + $p..."
        on line 21 of /Users/ricardo.dani/Development/sphinx_rtd_theme/bower_components/bourbon/dist/helpers/_linear-angle-parser.scss
        from line 10 of /Users/ricardo.dani/Development/sphinx_rtd_theme/bower_components/bourbon/dist/_bourbon.scss
        from line 11 of sass/badge_only.sass
  Use --trace for backtrace.
Syntax error: Invalid CSS after "      webkit-image": expected ")", was ": -webkit- + $p..."
        on line 21 of /Users/ricardo.dani/Development/sphinx_rtd_theme/bower_components/bourbon/dist/helpers/_linear-angle-parser.scss
        from line 10 of /Users/ricardo.dani/Development/sphinx_rtd_theme/bower_components/bourbon/dist/_bourbon.scss
        from line 16 of sass/theme.sass
  Use --trace for backtrace.
Warning: Exited with error code 1 Use --force to continue.

**Comment by Blendify** [comment]
Someone please close this report.
