### ISSUE TITLE
use an offline font?

### ISSUE THREAD

**Issue by abdelouahabb** [rtfd/sphinx_rtd_theme#161]
Hi,
Thank you for the beautiful theme, but it uses an online theme (`Inconsolata`) cant just embeed it localy when it is installed and copied with every project rendered?

**Comment by titilambert** [comment]
Hello ! I made a PR to fix it:  #143

**Comment by abdelouahabb** [comment]
ah, thank you ^_^

**Comment by waywardmonkeys** [comment]
Since the pull request #143 was merged, this bug can probably be closed?
