### ISSUE TITLE
Does not honour the .. meta:: directive.

### ISSUE THREAD

**Issue by fluffels** [rtfd/sphinx_rtd_theme#164]
# Steps To Reproduce

Create a file with the following at the top:

``` reStructuredText
.. meta::
      :description: The reStructuredText plaintext markup language
      :keywords: plaintext, markup language
```
# Result

No meta tags are generated.
# Expected result

Produced HTML should have meta tags like:

``` html
<meta content="The reStructuredText plaintext markup language" name="description" />
<meta content="plaintext, markup language" name="keywords" />
```
# Comments

The default theme handles this correctly.

**Comment by Blendify** [comment]
I am not sure when this started working but this now works.
