### ISSUE TITLE
Choosing pygments monokai style

### ISSUE THREAD

**Issue by lifeBalance** [rtfd/sphinx_rtd_theme#166]
Following the instructions given in [the sphinx docs](http://sphinx.readthedocs.org/en/latest/config.html#confval-pygments_style), in my `conf.py` I set:

```
# The name of the Pygments (syntax highlighting) style to use.
pygments_style = 'monokai'
```

But it doesn't work. Any ideas why? Thanks.

**Comment by patricksnape** [comment]
Can confirm that this doesn't work (Sphinx==1.3b2, sphinx-rtd-theme==0.1.6, Pygments==2.0.2) using the Napolean extension, on Ubuntu 14.04 x64.

**Comment by frol** [comment]
It is because RTD packages pygment styles inside its theme.css:
https://github.com/snide/sphinx_rtd_theme/blob/master/sass/theme.sass#L45
Here is the file (https://github.com/snide/wyrm/blob/master/sass/wyrm_addons/pygments/_pygments_light.sass)

**Comment by lifeBalance** [comment]
Thanks frol. But I don't get it. How can I change the pygments style?

**Comment by frol** [comment]
@lifeBalance While it has to be fixed in RTD theme, there is a workaround.
Create `source/_templates/layout.html` tempate with the following content:

```html
{# layout.html #}
{# Import the theme's layout. #}
{% extends "!layout.html" %}

{% set css_files = css_files + ['_static/pygments.css'] %}
```

Then your `pygments_style` variable in the `conf.py` will take effect.

**Comment by oliver-sanders** [comment]
Note that the workaround https://github.com/rtfd/sphinx_rtd_theme/issues/166#issuecomment-73278320 results in a mixed style. Attributes like font weight / style will likely leak from the RTD style into the pygments style.
