### ISSUE TITLE
Text is not shown on website in Firefox

### ISSUE THREAD

**Issue by mtdowling** [rtfd/sphinx_rtd_theme#171]
This issue was opened on my repo that uses the readthedocs theme: https://github.com/guzzle/guzzle/issues/984

From the user:

> It looks like I have a local installation of Lato font, which is used on this website, but for some reason text is not rendered. I'm using latest Mozilla Firefox on Ubuntu.

**Comment by stphnpt** [comment]
Same issue linked to Firefox policy on font files:

Downloadable font: **rejected by sanitizer** (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:1) source: mysite/doc/_static/fonts/fontawesome-webfont.woff?v=4.2.0 theme.css:4:14
downloadable font: rejected by sanitizer (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:2) source: mysite/doc/_static/fonts/fontawesome-webfont.ttf?v=4.2.0 theme.css:4:14
downloadable font: no supported format found (font-family: "FontAwesome" style:normal weight:normal stretch:normal src index:4) source

**Comment by Blendify** [comment]
Closing this issue. If you still experience the issue after the next release (0.2.5) please reopen this issue.
