### ISSUE TITLE
Table of Contents Not Displaying

### ISSUE THREAD

**Issue by joekayaker** [rtfd/sphinx_rtd_theme#176]
First let me say "Thanks!" for a beautiful modern theme. Good job!

I've locally ported documentation to sphinx_rtd_theme from previous Sphinx themes (classic, pydoctheme). The table of contents showed properly in those themes, but doesn't appear in sphinx_rtd_theme. I've read the documentation on toctree and am pretty sure I have it correct. Is anyone else having this problem? 

I have a very simple project that is only documenting one python module with one .rst.

**Comment by kxxoling** [comment]
Is there any way to reappear this issue? Show us an online demo.

**Comment by joekayaker** [comment]
kxxoling,
Sorry it took me so long to get back to you. I've created a repository (https://github.com/joekayaker/sphinx_rtd_theme_issue176) for some "sample" files that I developed in order to show the issue. It will be obvious that the code is imaginary.

I've just started using reStructuredText so it could definitely be something I'm doing wrong and not the theme itself. I'm also a relative newbie to Python so my functions may not look pretty or well optimized to a Python master.

**Comment by Swader** [comment]
@joekayaker @kxxoling I am seeing this issue, too. Starting a new project with this theme, grabbing [this](https://github.com/guzzle/guzzle/blob/master/docs/overview.rst) and [this](https://github.com/guzzle/guzzle/blob/master/docs/qiuckstart.rst) as demo files, and building HTML with the following `index.rst` file:

```
.. Test documentation master file, created by
   sphinx-quickstart on Sat Aug  8 20:15:44 2015.
   You can adapt this file completely to your liking, but it should at least
   contain the root `toctree` directive.

Welcome to Test's documentation!
================================

Contents:

.. toctree::
   :maxdepth: 2

   overview
   quickstart
```

gives me docs which have the ToC available only when I'm on the master file (index) but as soon as I click a heading to go to another file, the ToC in the left menu disappears.

Let me know if there's a potential setting I may have missed.

**Comment by Swader** [comment]
Interestingly, after upgrading my `conf.py` file to get PHP syntax highlights with this:

```py
from sphinx.highlighting import lexers
from pygments.lexers.web import PhpLexer
lexers['php'] = PhpLexer(startinline=True, linenos=1)
lexers['php-annotations'] = PhpLexer(startinline=True, linenos=1)
primary_domain = 'php'
```

and rebuilding, I got it working.

Curiously, even if I remove those parts and force a rebuild on all files instead of only outdated ones, the TOC still sticks around - it's fine. So I guess it's all about getting it to work that one time.

**Comment by Swader** [comment]
Having added another file and thus another heading for the TOC, I noticed the QuickStart and Overview TOC entries were still there when I accessed the new document, but when I went into Quickstart or Overview, the new heading was not there. This makes me think the left sidebar is not being rebuilt for older documents, not even by force (tried `sphinx-build -a` to force a rebuild).

**Comment by Blendify** [comment]
Is anyone still experiencing this issue? If not I am going to close this issue.

**Comment by kacann** [comment]
I am having the same issue. When I change an existing file, the new TOC entry appears. But if I don't change a file (such as by adding extra lines at the end), I lose the newest TOC entry when I click the heading for that file.

**Comment by JoshuaPostel** [comment]
+1 experiencing the behavior described by @Swader

**Comment by alisianoi** [comment]
I am experiencing this issue with:

```
sphinx 2.2.2
sphinx-rtd-theme 0.4.3 
```
The `sphinx_rtd_theme` was installed as a Python package with `pip install sphinx_rtd_theme` and then the `conf.py` file was updated for two variables:

```
extensions = [
    'sphinx_rtd_theme',
]

html_theme = 'sphinx_rtd_theme'
```

## Bug Behaviour

I have three entries in my Contents section. Whenever I click entry number two or number three, entry number one disappears. The only way to bring the first entry back is to click on the home link at the top (see GIF from comment above https://github.com/readthedocs/sphinx_rtd_theme/issues/176#issuecomment-129161616)

**Comment by Nordup** [comment]
Removing build directory and rebuilding it works. Thanks!
