### ISSUE TITLE
Sphinx default theme changed

### ISSUE THREAD

**Issue by jcrmatos** [rtfd/sphinx_rtd_theme#179]
Hello,

Just updated to Sphinx 1.3.1 and found out that it's default theme changed to 'alabaster'.
The old default is now called 'classic'.

However, if I change html_theme to 'classic', RTD does not build.
Can you update it to accept both the old and the new names ('default' and 'classic')?

Thanks,
JM

**Comment by xuhdev** [comment]
I think this project has nothing to do with rtd build system.... This is just the rtd theme.

**Comment by Blendify** [comment]
I is not something that we can/will change please close this report.
