### ISSUE TITLE
Not responsive in larger screens

### ISSUE THREAD

**Issue by rougin** [rtfd/sphinx_rtd_theme#207]
Hello! It seems that the theme is not responsive in larger screens. My current screen resolution is `1920x1080`.

![untitled](https://cloud.githubusercontent.com/assets/6078637/8155088/917e2428-12f5-11e5-80c1-cde4e18c9c9d.png)

**Comment by rougin** [comment]
Even also in my generated documentation.

![untitled](https://cloud.githubusercontent.com/assets/6078637/8155174/623df336-12f6-11e5-990d-d368f4e2e0d9.png)

**Comment by Blendify** [comment]
See discussion on https://github.com/rtfd/sphinx_rtd_theme/pull/209
