### ISSUE TITLE
Scroll to active item in sidebar on load

### ISSUE THREAD

**Issue by lazka** [rtfd/sphinx_rtd_theme#214]
As an example: https://quodlibet.readthedocs.org/en/latest/development/maint.html

It would be nice if the sidebar item I have just clicked on would still be in view on my small screen after the page is loaded. Maybe scroll to the active item in the sidebar on load with some javascript?

**Comment by agjohnson** [comment]
We have plans to improve this more on a future release. It currently has some ability to scroll to the correct element, but there should be better focusing on the nav element when items are clicked, or entering a page like this.

**Comment by agjohnson** [comment]
Looks like the feature that does exist might have regressed in addition. Clicking on a menu item, even L1, doesn't auto scroll the menu down now.

Ref rtfd/readthedocs.org#4474
