### ISSUE TITLE
Edit on GitHub page links to rst document even though source is in md

### ISSUE THREAD

**Issue by KarolKaczmarek** [rtfd/sphinx_rtd_theme#227]
Hi,
I followed instructions from https://read-the-docs.readthedocs.org/en/latest/getting_started.html to add support for both rst and md.

The problem is that when I go to page which source is in markdown, e.g. `getting-started/index.md`, `Edit on GitHub` link will take me to file `getting-started/index.rst` on my github repository which doesn't exist and displays HTTP 404 instead. 

Are there any additional steps necessary to get it to work?

Thanks!

**Comment by cmdcolin** [comment]
Would also be interested in this!

**Comment by willingc** [comment]
The cause was an underlying bug in Sphinx which has been fixed as 1.3.6. See issue and resolution here https://github.com/sphinx-doc/sphinx/pull/1876
