### ISSUE TITLE
Changes to toctree doesn't trigger rebuild of all pages

### ISSUE THREAD

**Issue by EvanPurkhiser** [rtfd/sphinx_rtd_theme#229]
I suspect I might have a configuration problem, but when I make changes to my `toctree` in `index.rst` it doesn't rebuild all of the pages in order to update the sidebar navigation for each like I would expect.

So for example, one page might have a newer / older navigation than another.

My `toctree` looks like this:

``` rst
.. toctree::
    :hidden:

    self
    errors
    authentication
```

Am I missing anything obvious, or perhaps this is a known problem

**Comment by Blendify** [comment]
Please report this issue to sphinx, this is not an issue with the theme.
https://github.com/sphinx-doc/sphinx
