### ISSUE TITLE
Transfer sphinx_rtd_theme repository to readthedocs.org organization

### ISSUE THREAD

**Issue by gregmuellegger** [rtfd/sphinx_rtd_theme#240]
I find it unintuitive that the `sphinx_rtd_theme` repository is not part of the `readthedocs.org` organization. IMO it looses discoverability and visibility from not being part of the de-facto owning organization (for example I'm watching the `readthedocs.org` organization to not miss updates, however I'm missing out on the theme updates since it lives somewhere else).

I understand that it is currently part of @snide's repository as he is the original creator and having the repo in his namespace is a matter of attribution. When moving the respository, we can mention @snide prominently in the README as a compromise for the lost attribution.

**Comment by denisvm** [comment]
Perhaps it could be forked there to maintain the original author reference and keep it updated there.
