### ISSUE TITLE
Modernizr is not used

### ISSUE THREAD

**Issue by mitya57** [rtfd/sphinx_rtd_theme#245]
Hi, I wonder why does RTD theme use `modernizr.min.js` file.

I tried grepping JS files for usage of `Modernizr` object, and SASS files for typical Modernizr `.foo` and `.no-foo` classes, but could find neither of them.

Is Modernizr really used anywhere? If the answer is no, then I'll be happy to provide a pull request to get rid of it.

**Comment by Blendify** [comment]
Closing, see discussion in PR.
