### ISSUE TITLE
adding links to the sidebar

### ISSUE THREAD

**Issue by anarcat** [rtfd/sphinx_rtd_theme#254]
is there a way to add a bunch of links to the sidebar in this theme? i would like to add links to the mailing list, bugtracker, releases of the project and so on... it seems that using `html_sidebars` doesn't work because the ones used there are only the ones shipped in the sphinx_rtd_theme..

**Comment by zhanghongyi** [comment]
@anarcat Would you mine me jumping into the thread? :)

I am not sure if the theme has built-in support for this functionality, but it seems to me you can simply add some html into layout.html under sidebar section to achieve this.

**Comment by anarcat** [comment]
@zhanghongyi i don't mind at all! :)

the problem with modifying the theme is that this won't show up on readthedocs.org directly, only on local instances... i'd like to add stuff to the sidebar on readthedocs.org...

thanks for the advice anyways! :)

**Comment by zhanghongyi** [comment]
@anarcat now I see the problem. cuz I only used the local version so far, I did not know that it would have trouble on readthedoc.org. :)

**Comment by Blendify** [comment]
I think this is more of a sphinx issue. Like https://github.com/sphinx-doc/sphinx/pull/1800 or https://github.com/sphinx-doc/sphinx/pull/2354 or https://github.com/sphinx-doc/sphinx/issues/701
