### ISSUE TITLE
guilabel role CSS style

### ISSUE THREAD

**Issue by DavidePrincipi** [rtfd/sphinx_rtd_theme#262]
The [guilabel role](http://sphinx-doc.org/markup/inline.html#role-guilabel) is displayed as italic by  the default Sphinx theme. Unfortunately, the RTD theme does not apply any emphasis, so it appears as normal text.

For instance, see "Owning group" in

http://docs.nethserver.org/en/latest/shared_folder.html#access-privileges 

```
<span class="guilabel">Owning group</span>
```

Is it possible to retain the default Sphinx style?

**Comment by Blendify** [comment]
This has been merged see https://github.com/snide/sphinx_rtd_theme/commit/101a2970f2b4af0869616b8e049e8b52f816cc1a someone please close.
