### ISSUE TITLE
"methods" and "attributes" sections not handled beautifully

### ISSUE THREAD

**Issue by cmeeren** [rtfd/sphinx_rtd_theme#263]
See ~~[this page](http://apexpy.readthedocs.org/en/latest/reference/Apex.html#apexpy.Apex.convert)~~ **the image in the next post**. Below the parameters section I have a Methods section and then an Attributes section.
- the headings are not shown (where does one section end and the other start? only way to see that is to look at the parentheses at the end)
- the text is rather large
- the methods are not linked to their documentation further down on the page

There is also an empty auto-generated table of methods in alphabetical order on that page, but that's another issue (#264).

**Comment by cmeeren** [comment]
Here's an image:

![rendered](https://cloud.githubusercontent.com/assets/7766733/11312039/d9cb00d8-8fd3-11e5-82c0-2c5b3e9774f7.png)

**Comment by cmeeren** [comment]
And here's the source:

````
class Apex(object):
    '''Performs coordinate conversions

    The most common methods are :meth:`~apexpy.Apex.convert` to convert between
    all supported coordinate systems, :meth:`~apexpy.Apex.map_to_height` to perform
    mapping along a field line to the closest or conjugate hemisphere, and
    :meth:`~apexpy.Apex.basevectors_qd` and :meth:`~apexpy.Apex.basevectors_apex` to
    calculate base vectors.

    Parameters
    ==========
    date : float (decimal year) or instance of :class:`~datetime.date` or :class:`~datetime.datetime`
        IGRF coefficients are used in conversions. Uses current date as default.
    refh : float
        Reference height in km for apex coordinates (the field lines are mapped to this height)
    datafile : str
        Path to custom coefficient file

    Methods
    =======
    convert
        High-level, general-purpose conversion between geodetic, modified apex, quasi-dipole and MLT
    geo2apex, apex2geo, geo2qd, qd2geo, apex2qd, qd2apex, mlon2mlt, mlt2mlon,
        conversion functions for specific coordinate systems (called by :meth:`~apexpy.Apex.convert`)
    map_to_height
        Maps geodetic coordinates along the magnetic field to a new height in the closest or conjugate hemisphere
        (for finding footprints, conjugate points, etc.)
    basevectors_qd, basevectors_apex
        Calculate base vectors
    get_apex
        Compute field line apex from apex latitude
    set_epoch, set_refh
        Change epoch and reference height for subsequent conversions

    Attributes
    ==========
    year : float
        Decimal year used for the IGRF model
    refh : float
        Reference height in km for apex coordinates
    datafile : str
        Path to coefficient file

    '''
````

**Comment by cmeeren** [comment]
I ended up removing the "methods" section, and for the the "attributes" section I set ``napoleon_use_ivar=True`` in conf.py and it looked the same as the Parameters section (much better IMHO).

**Comment by Blendify** [comment]
> the headings are not shown (where does one section end and the other start? only way to see that is to look at the parentheses at the end)

This is not supported by sphinx; not a theme issue, maybe try `.. rubric::`?

> the text is rather large

This is not really an issue in the theme but more of a personal preference. I would recommend changing overriding this yourself with CSS.

> the methods are not linked to their documentation further down on the page

This seems to be working now.

---------

Anyway, I addressed all the points and will close the task.
