### ISSUE TITLE
Returns/Return type headers not correctly vertically aligned with content

### ISSUE THREAD

**Issue by cmeeren** [rtfd/sphinx_rtd_theme#265]
See the image below (from [this page](http://apexpy.readthedocs.org/en/latest/reference/Apex.html#apexpy.Apex.geo2apex)). In the first two methods, the content in the Returns and Return type sections are not correctly vertically aligned with their headers. In the third method, it looks correct. Using Windows 10 with Firefox 42.0, Chrome 46.0 and Microsoft Edge.

![rendered](https://cloud.githubusercontent.com/assets/7766733/11313049/719895e6-8fda-11e5-9c66-2b796b0ce02d.png)

**Comment by Blendify** [comment]
This should be fixed in c99e5d2e8d626790f32e990621142318e6f5dcfe if not please re open this issue after the 0.2.5 release.
