### ISSUE TITLE
Upgrade/decouple font-awesome?

### ISSUE THREAD

**Issue by mixmastamyk** [rtfd/sphinx_rtd_theme#266]
Hi,

I'd like to use some new icons from the latest font awesome.  Is there a way to decouple it from this project and use a package on PyPi instead?  So we wouldn't have to bother you to update?  ;)

**Comment by Blendify** [comment]
Closing this, this is not really something we are willing to support right now with limited development. Currently, we are using version 4.6 and will be updated to 4.7 with https://github.com/rtfd/sphinx_rtd_theme/pull/377
