### ISSUE TITLE
Definition list items have inconsistent row-spacing

### ISSUE THREAD

**Issue by honzajavorek** [rtfd/sphinx_rtd_theme#271]
<img width="749" alt="screen shot 2015-12-06 at 00 37 37" src="https://cloud.githubusercontent.com/assets/283441/11610886/e8a1aafa-9bb1-11e5-8643-37ecc5809e3c.png">

Seems like items with multiple paragraphs get larger row-spacing than items with just single paragraph. If these get mixed, the output looks inconsistent and ugly.

**Comment by agjohnson** [comment]
Yup, correct. Seems the paragraph styling should also apply to the `dl -> dd` elements.

**Comment by jessetan** [comment]
Can no longer reproduce this, closing.
Please reopen if this is still an issue.
