### ISSUE TITLE
Derivated theme

### ISSUE THREAD

**Issue by dogoepp** [rtfd/sphinx_rtd_theme#272]
Hi snide,

First, thank you for this great theme. We really appreciate it and it's why we want to modify it for your project. It would become a new theme since features, layout and colours will be changed, even though the changes are far from major.

Therefore, I would like to know how you consider it respectful to credit your work ? Of course your name is in Bower.js and I'll add your name in the README.

Best regards,
Dorian

**Comment by agjohnson** [comment]
@dogoepp If there are added features, why implement in a separate theme?

**Comment by dogoepp** [comment]
Well, it is indeed more changes than mere added features. For instance, 
I disabled (in a dirty way) the folding of the table of contents.

The only things that could be called features are:

- create two theme parameters to add links either above or bellow the 
table of contents
- change the URL to which the "home" link, or logo points (with a theme 
parameter)

Would you be interest by such features ?

Furthermore, the changes I made are not only in the HTML templates but 
also in the SASS files. I do not see how I could change them without 
changing the theme.

**Comment by Blendify** [comment]
The theme is licensed under the MIT license see https://opensource.org/licenses/MIT for more information
