### ISSUE TITLE
Sidebar image not displaying correctly on Firefox (low-res)

### ISSUE THREAD

**Issue by bazzinotti** [rtfd/sphinx_rtd_theme#288]
please read the full discussion at mitmproxy/mitmproxy#1077

**Comment by raffomania** [comment]
After seeing this too, upgrading firefox to version 46.0.1 fixed it for me. 
Can you confirm?

**Comment by bazzinotti** [comment]
@raffomania What did you use to test it? Mitmproxy has patched their doc image as stated in the linked issue discussion, so I have no test material.

**Comment by raffomania** [comment]
I'm afraid this was for a private repo, so I can't give a link. 
If no one else has experienced this, maybe we can just close it ;)

**Comment by bazzinotti** [comment]
well don't just do that! Give me some time :+1:

**Comment by Blendify** [comment]
Closing this, if you still have an issue please reopen this.
