### ISSUE TITLE
monospace font without background change

### ISSUE THREAD

**Issue by smoser** [rtfd/sphinx_rtd_theme#298]
I would like to use a monospace font to format literals or command line arguments, but feel that the default rendering of `--my-monospace` is distracting to reading because of the change in color and background (as seen in the [rtd docs](http://read-the-docs.readthedocs.io/en/latest/theme.html)).

Is it possible to have simply change the font or some other way that makes the text stand out but does not distract so much?  As an example of what I'm after, you can open up just about any old O'Reilly book and see.

I do realize that this is highly personal preference.

**Comment by Blendify** [comment]
I discussed this with @agjohnson and we decided to keep the default rendering for now. But you can override it in css see https://github.com/rtfd/sphinx_rtd_theme/issues/358 for more information on this.
