### ISSUE TITLE
Move 1400px media-query to 1100px ?

### ISSUE THREAD

**Issue by Carreau** [rtfd/sphinx_rtd_theme#305]
The `.wy-nav-content` wraps at 1100px width when above 1400px+  wide, and has a linear growth until this value, which make the website "jump" when you reach the 1400px width threshold. 

Which is then weid as a 1401px wide window has narrower content than a 1399 one...

I think the theme should either move the 1400px transition to 1100px. THen the content just "stop growing", or change the max-width of `wy-nav-content` to be higher by 300px. 

Both looks fine. I can likely make a PR depending on the one you prefer.

**Comment by Blendify** [comment]
Personally, I think that we should extend the width by 200px and decrease the media query by 100px? We should also when fixing this write a function so this can be changed easier.
