### ISSUE TITLE
Option not to include headings in the toctree

### ISSUE THREAD

**Issue by akien-mga** [rtfd/sphinx_rtd_theme#312]
This is a follow-up to #277 which was just fixed by adding the `navigation_depth` option. I've noticed that though this option is quite useful to have, it doesn't fully address my use case when using `collapse_navigation = False` (i.e. tree-like structure).

What I'd like to have as an option is to be able to limit the table of contents sidebar to sections and pages, without showing the various levels of headings/subsections for pages.

Basically I'd like the toctree to only display, where `+` shows an expandable item, and `o` shows a non-expandable item.

```
+ Section 1
   + Subsection 1.1
      o Page 1.1.1
      o Page 1.1.2
    o Page 1.2
```

instead of:

```
+ Section 1
   + Subsection 1.1
      + Page 1.1.1
         o Heading2 1.1.1.1
         + Heading2 1.1.1.2
            o Heading3 1.1.1.1.1
         o Heading2 1.1.1.3
      o Page 1.1.2
    + Page 1.2
       o Heading 1.2.1
```

Some examples to be more explicit:
- This looks good in the sidebar, as what is uncollapsed shows only subsections: http://docs.godotengine.org/en/latest/tutorials/engine/_engine.html
- This is not good, as what is uncollapsed shows individual pages as uncollapsable, which gives the impression that they are subsections (and thus that there are an overwhelming amount of tutorials to read): http://docs.godotengine.org/en/latest/tutorials/step_by_step/_step_by_step.html
- Another example where the verbosity can be in our opinion quite misleading to users; all the uncollapsed items here are pages or h2/h3, even though they look like subsections: http://docs.godotengine.org/en/latest/reference/compiling_for_universal_windows_apps.html#compiling

Using `collapse_navigation = True` works this around thanks to the properly defined `:maxdepth:`, but we really want to use this tree-like navigation. What we'd need for our use case is an option that ignores page headings (h2 and later) when generating the toctree, but only takes into account the page and section titles (h1).

The `navigation_depth` parameter does not fully address our use case, as we need variable depths depending on the section (e.g. our "Learning step by step" section needs a depth of 2, while our "Engine" section with its subsections needs a depth of 3).

Hope this makes sense, and thanks for your work on this theme :)

**Comment by reduz** [comment]
To put a little more context, a single page such as this:

![image](https://cloud.githubusercontent.com/assets/6265307/17005514/0d868f72-4eb1-11e6-8a24-c98d90a96af7.png)

shows a ton of sections and subsections at the toc:

![image](https://cloud.githubusercontent.com/assets/6265307/17005528/1fc314c6-4eb1-11e6-9be5-75540acee1a8.png)

Making the toc huge and very confusing to browse, specially in documentations as large and complex as ours. Simply not showing the headings at all in the toc would be fantastic.
