### ISSUE TITLE
consider moving this repo to the rtfd org

### ISSUE THREAD

**Issue by whit537** [rtfd/sphinx_rtd_theme#325]
I went [looking](https://github.com/AspenWeb/aspen.py/pull/32#issuecomment-246147438) for this repo. First, I looked under https://github.com/readthedocs. I was confused at seeing _some_ repos but not the ones I expected, then I noticed "http://github.com/rtfd houses ..." in the sidebar. I went to http://github.com/rtfd, but still didn't find this repo. Then I scratched my head, and thought back, and recalled that yes, the theme repo was in a different org ... wasn't it? A google search brought me here, but from the outside it seems that a Sphinx RtD theme would most naturally be housed under a RtD GitHub org. 🙇

**Comment by ericholscher** [comment]
@snide thoughts? I've had a couple requests from folks looking to get access to doing triage or other adminy type things on this repo as well. I can send those along for you to deal with, or we can move it over the the `rtfd` org and we can deal w/ it going forward.

**Comment by snide** [comment]
It's ok with me. You've obviously done the lions share of the work past my initial work.

**Comment by ericholscher** [comment]
@snide Believe you have to do it, since you're the owner -- https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-to-an-organization has the instructions. You should have proper perms in the `rtfd` organization, but let me know if it won't work.

**Comment by polyzen** [comment]
Related issue suggesting it be added to sphinx-doc instead: #293

**Comment by ericholscher** [comment]
@polyzen Thanks for pointing that out -- I think we'll keep it as an independent module for now.

**Comment by snide** [comment]
OK. So I'll move it? Any links or bits that will break if I do that @ericholscher. Can do it tonight, just wanna make sure there aren't any hard linked dependencies somewhere.

**Comment by ericholscher** [comment]
Believe GitHub should handle the redirects automatically.

**Comment by ericholscher** [comment]
Also, thank you! For moving things over, and for doing the original work. This theme has grown and expanded and is now everywhere. Well done! :)

**Comment by snide** [comment]
Done! No worries. Glad I could help and contribute what I could.
