### ISSUE TITLE
"logo_only: True" is not working on RTD

### ISSUE THREAD

**Issue by zefanja** [rtfd/sphinx_rtd_theme#341]
I've enabled the option `logo_only` like this in my `conf.py`:

`html_theme_options = {
    'logo_only': True
}`

The logo is showing on RTD, but also the title with the small house icon. (see here → http://docs.linuxmuster.net/en/latest/)

What do I wrong or is this a bug?

EDIT: If I set the theme with `html_theme = 'sphinx_rtd_theme'` it works. But isn't this the default theme on RTD? Is there way to get this working without setting the `html_theme` option?

**Comment by Blendify** [comment]
I do not think so.
