### ISSUE TITLE
:tocdepth: not working anymore (0.1.9)

### ISSUE THREAD

**Issue by parsch** [rtfd/sphinx_rtd_theme#347]
When updating sphinx-rtd-theme from 0.1.8 to 0.1.9 the `:tocdepth: <n>` directives at beginnings of `.rst` files [like here](https://raw.githubusercontent.com/sphinx-doc/sphinx/master/doc/authors.rst) seem to be ignored, they are not any longer reflected in the menu/submenus.

For example, a `.rst` file with a `:tocdepth: 3` specified always resulted in a menu/submenu structure down to 3 hierarchies. That's not the case anymore.

I first looked into sphinx itself and other dependencies but ended up with sphinx-rtd-theme being somehow responsible for that, esp. when it works with 0.1.8 and doesn't work with 0.1.9

**Comment by Blendify** [comment]
I think this has been fixed please try 0.2.2

**Comment by Blendify** [comment]
Closing this, if you are still having an issue we can reopen this issue.
