### ISSUE TITLE
How can I use this theme on ReadTheDocs?

### ISSUE THREAD

**Issue by Paebbels** [rtfd/sphinx_rtd_theme#350]
I have integrated this theme as a Git submodule into my repository. It contains simple modifications. How can I use this theme, because ReadTheDocs.org seams to overwrite my html theme settings?

**Comment by brianjking** [comment]
@Paebbels -- Make a ````_templates```` folder and save the files you modified inside of it. See a repo of mine where I overwrite several default files: https://github.com/duelingdogs/dueling-docs/tree/master/source/_templates

**Comment by Paebbels** [comment]
Hello Brian,

I think I found the issue. RTD reuses the build directory, thus it uses it uses cached files instead of new. My current conf.py deletes the _build directory.

Kind regards
    Patrick
