### ISSUE TITLE
How to remove extra space after image inclusion

### ISSUE THREAD

**Issue by Lopezo** [rtfd/sphinx_rtd_theme#352]
I am using Sphinx with the Read The Docs theme to build a website.

I include images on the right of a text with:
```
.. figure:: fig/image.png
:width: 150px
:align: right

Lorem ipsum ...
```

The result obtained after compilation is visible here on a [stackoverflow question]( http://stackoverflow.com/questions/40992459/in-read-the-docs-theme-build-with-sphinx-how-to-remove-extra-space-after-image). There is a blank line after the image.

My question is: how to remove the extra blank line after the image.png?

**Comment by Blendify** [comment]
I think you have to change the bottom margin of `.figure` in you theme override file. However, not sure how this would look with captions

**Comment by Lopezo** [comment]
In that particular case, it was: `.section>a>img{margin-bottom:0px}`
