### ISSUE TITLE
Moving\importing from another place RTD theme

### ISSUE THREAD

**Issue by walter1938** [rtfd/sphinx_rtd_theme#356]
Hi.

Right now i'm facing a trouble when i did some minor changes to layout.html and add some extra.js file to a static folder of the theme, but i need the whole theme to be moved to a specific git project folder, so anyone could clone my repository and easily build a documentation including those changes. I suppose there are two possible ways of getting out of this situation:

1. Move changed RTD theme to the git project folder, so it could be always available in the repository.
2. Create a small custom theme that includes the extra.js file and somehow inserts one <script> tag in a <body> tag of the layout.html file.

But in both ways i don't really know how to do it. Maybe, someone could suggest me a solution? I'd be really grateful.

P.S. All those changes i mentioned above are about adding a timestamp in docs' URL so it won't be cached.

Thanks in advance.

**Comment by Blendify** [comment]
This is really not the place to be asking this. Maybe try http://stackoverflow.com/ anyway please close this.
