### ISSUE TITLE
Font awesome links in badge_only.css are broken

### ISSUE THREAD

**Issue by toolness** [rtfd/sphinx_rtd_theme#359]
I stumbled into this when attempting to add a generated site using `sphinx_rtd_theme` to my Django project's static files dir; its `ManifestFileStorage` throws errors if CSS files contain URLs to non-existent files, and it seems this is the case with the [`static/css/badge_only.css`](https://github.com/snide/sphinx_rtd_theme/blob/master/sphinx_rtd_theme/static/css/badge_only.css) file, which references the following URL:

```
../font/fontawesome_webfont.eot
```

However, the project's font  directory is called [`fonts`](https://github.com/snide/sphinx_rtd_theme/tree/master/sphinx_rtd_theme/static/fonts) (plural) and the file it's looking for has a hyphen instead of an underscore in it (it's called [`fontawesome-webfont.eot`](https://github.com/snide/sphinx_rtd_theme/blob/master/sphinx_rtd_theme/static/fonts/fontawesome-webfont.eot)). This is also the case with the `.woff`, `.ttf`, and `.svg` versions of the file.

**Comment by toolness** [comment]
For what it's worth, I'm interested in submitting a PR to fix this, just let me know!

Right now I'm working around it on my end by running the following after building the docs:

```bash
sed -i.bak 's/font\/fontawesome_/fonts\/fontawesome-/g' \
  $(BUILDDIR)/html/_static/css/badge_only.css
```

**Comment by Blendify** [comment]
I can confirm this issue also.

**Comment by Blendify** [comment]
@toolness I can also make a fix for this but if you are still up for it go for it.

**Comment by toolness** [comment]
Woot thanks for fixing this @Blendify!

**Comment by Blendify** [comment]
No problem
