### ISSUE TITLE
"Previous" and "Next" translation

### ISSUE THREAD

**Issue by ricpelo** [rtfd/sphinx_rtd_theme#360]
How can I translate "Previous" and "Next" buttons into Spanish so I can see them translated in local as well as in "read the docs" hosting? Thank you very much!
![2017-02-10-194729_1276x610_scrot](https://cloud.githubusercontent.com/assets/616169/22839514/0cee0be8-efca-11e6-9d2f-f92cd6bc5529.png)

**Comment by Blendify** [comment]
I am not 100% sure but I think you need to use http://www.sphinx-doc.org/en/stable/config.html#confval-language

**Comment by ricpelo** [comment]
@Blendify thanks for your reply. Unfortunately, I get `language='es'` in my `conf.py` but these strings aren't translated. May I need to do some additional steps?

**Comment by Blendify** [comment]
What version of the theme are you using? it seems there was a recent comment (https://github.com/snide/sphinx_rtd_theme/commit/e43226965eaf694551940cc7a0adae6b72bd8387) which only seems to be on 0.2.0 and up.

**Comment by rbideau** [comment]
Hi, I'm using version 0.2.4 (installed via package) with the `language` setting and I have the same issue: "Next" and "Previous" button are not translated. But neither  "Search doc" and "Built with Sphinx...".

**Comment by jordicasadevall** [comment]
I have the same problem, when I do "make html", a "translations.js" is generated for each locale and it works, but some texts as "previous" or "next" are missing. How can I add these translations?

**Comment by Blendify** [comment]
Closing see #403

**Comment by ecekaya** [comment]
Hi, Is there anyone who can solve this issue? I have the same problem. The language is 'tr' on `conf.py`. But prev-next buttons, "Search Docs" are still English. How can I translate them?
