### ISSUE TITLE
Spacing on line-numbering for pre blocks is broken

### ISSUE THREAD

**Issue by njsmith** [rtfd/sphinx_rtd_theme#381]
It looks like #344 (fixing #329) changed the vertical spacing of pre blocks. Unfortunately, it *didn't* change the vertical spacing of the corresponding line numbers, so now they're out of sync:
![broken-linenos](https://cloud.githubusercontent.com/assets/609896/23698389/36f7fac2-03a0-11e7-89bf-4fc325a52abe.png)

I guess that in addition to applying to `.highlight > pre`, we need the new code in #344 to apply to `.linenodiv > pre`?

**Comment by skirpichev** [comment]
@njsmith, is this that you mean
```css
.linenodiv > pre
    line-height: normal
```
?

**Comment by njsmith** [comment]
Yes, I think so.
