### ISSUE TITLE
Odd vertical spaces in pre elements (2nd attempt)

### ISSUE THREAD

**Issue by skirpichev** [rtfd/sphinx_rtd_theme#407]
Same issue as #329, which was fixed, so I can't reproduce this issue on my local setup with v0.2.4 of the theme.

However, this issue still present on the rtd, see matrix example at the bottom of the [introduction](http://diofant.readthedocs.io/en/latest/tutorial/intro.html) page: 
![1](https://cloud.githubusercontent.com/assets/2155800/24589491/45110f26-17ec-11e7-96b3-57470caf842b.png)

@Blendify, [told me](https://github.com/rtfd/sphinx_rtd_theme/pull/382#issuecomment-290786575) that installed on the rtd theme now is up to date (i.e. v0.2.4).  But apparently, something doesn't work.

**Comment by Blendify** [comment]
Ok we finally traced the issue and will be fixed tomorrow on RTD.

**Comment by skirpichev** [comment]
Now works.  Thank you.

![1](https://cloud.githubusercontent.com/assets/2155800/24647212/0dbb7846-1930-11e7-81d0-69e7870fc9b0.png)
