### ISSUE TITLE
enumerate render error: second line for item sticks to next item; leaves some space

### ISSUE THREAD

**Issue by SimJoSt** [rtfd/sphinx_rtd_theme#408]
I noticed on the current changelogs of Gluon (https://gluon.readthedocs.io/en/v2016.2.2/releases/v2016.2.2.html#bugfixes), that the list/enumerate is not rendered correctly.
Some of the list items have a second line without being the next item. Instead of being rendered directly underneath the item they belong to, they seem to stick to the top of the next item with a little space to the previous item.

**Comment by Blendify** [comment]
This is because there is a new line in the rst file. Closing.

**Comment by SimJoSt** [comment]
@Blendify I agree that this warrants the space between the enumerated item and the plain text after. But between the plain text and the next enumerated item is also a new line.  
This should also create some space, like between the other 2 sections.
