### ISSUE TITLE
sphinx_rtd_theme is not getting applied on the Master branch (ReadTheDocs) builds 

### ISSUE THREAD

**Issue by veenamj** [rtfd/sphinx_rtd_theme#416]
Hi, 

I am facing a strange problem. I added latest sphinx_rtd_theme files on to my project and did the required theme overrides (including the well-known text wrapping within the tables). 

The local build works absolutely fine. But it was pushed to the master, the theme goes back to very basic and it is not getting applied. I tried manual builds but still I could not trace the root cause and the workaround. 

By master, I mean the builds that are created on the ReadTheDocs website (account).   

Any help is greatly appreciated. Thanks in Advance.

**Comment by Blendify** [comment]
Please try using the new beta that is out 0.2.5beta

**Comment by veenamj** [comment]
This is closed.
