### ISSUE TITLE
how to see, if link is external

### ISSUE THREAD

**Issue by kassbohm** [rtfd/sphinx_rtd_theme#427]
can I show in my documentation, that a link is an external link -- e.g. as below. Do I have a **html_theme_options** for this? This is a question, but I think, I can't tag it as such, can I? this being another question...

![screenshot](https://cloud.githubusercontent.com/assets/1640233/26759566/92f99a66-4909-11e7-86e2-d5079f72a53a.png)

**Comment by Blendify** [comment]
There is actually code for this, however, it is commented out in the code for the following reason:
`Questionable whether this is nice or not. It styles external links, but comes with some baggage.`
IMO this is fine but like to hear some other people's thought. @ericholscher @agjohnson  ???

**Comment by ericholscher** [comment]
Hmm, I really appreciate that type of styling, so I'm not sure the complications. I'd be +1 on it generally.
