### ISSUE TITLE
Help porting a Stylish theme to the official repo

### ISSUE THREAD

**Issue by CrazyPython** [rtfd/sphinx_rtd_theme#435]
I created a (work in progress) Sylish theme that overhauls the CSS:
![](https://i.imgur.com/KuTTgG0.png)

Without the theme:

 ![without the theme](https://i.imgur.com/rRRcCJo.png)

Assuming you're willing to accept these changes (I certainly hope so 😄 ), could I receive some help porting it to the official theme? (since I'm not familiar with the codebase)

[(you can find the theme here)](https://userstyles.org/styles/144136/material-for-read-the-docs)

**Comment by Blendify** [comment]
I would be against adding this in a way such as a toggle. One thing we are wanting to do is be able to modify some basic CSS properties in the configuration file. In order for us to start this, we need to merge https://github.com/rtfd/sphinx_rtd_theme/pull/404

**Comment by CrazyPython** [comment]
@Blendify 

> I would be against adding this in a way such as a toggle.

Could you clarify?

**Comment by Blendify** [comment]
I would rather allow users to easily change major theme colors rather than distributing other sub-themes. Or if we do we can simply distribute different theme.conf files.

**Comment by CrazyPython** [comment]
@Blendify Good idea- perhaps the default theme should look better, though?

**Comment by Blendify** [comment]
There are a few tweaks that I have been merging in but overall I think it is still the cleanest Sphinx theme.

**Comment by CrazyPython** [comment]
@Blendify What about making the text body full-width and making the search box square?

**Comment by tuukkamustonen** [comment]
I think a full-width body is bad for readability and rounded vs square search box is irrelevant (=you'll find as many opinions as people...)

**Comment by Blendify** [comment]
Being able to optionally change it is something I would like to see us support.

**Comment by polyzen** [comment]
@Blendify, that could be nice, for pages with long lines of code or better handling of zoomed-in contents.

I don't see how this theme looks better, otherwise. Almost everything has been changed, and the contrast is jarring.

**Comment by vinay87** [comment]
@Blendify is that option available now? I'd like to be able to change the color to match my company's standard color options without hacking my way around the code too much.

**Comment by Blendify** [comment]
No once #404 gets merged we can add more customization options. In the meantime, this is a general todo (see the readme) so there is no need to keep this open.
