### ISSUE TITLE
incorrect text - math - text punctuation

### ISSUE THREAD

**Issue by kassbohm** [rtfd/sphinx_rtd_theme#439]
Lines are not properly broken, if I have a full stop (period) or a comma directly after using
`:math:` role for inline math.

If I use `:math:` to set v to be a **math** symbol like this:

![screenshot-2](https://user-images.githubusercontent.com/1640233/28112435-abe318fc-6701-11e7-870a-953379230781.png)

then I get an incorrect text - math - text punctuation:

![screenshot](https://user-images.githubusercontent.com/1640233/28111890-bb03f4c0-66ff-11e7-9e05-68596f1fe6cd.png)

If I **dont** use `:math:` and let v be **text** like this:

![screenshot-3](https://user-images.githubusercontent.com/1640233/28112496-eac98704-6701-11e7-8acb-cd005852615d.png)

then the punctuation is correct:

![screenshot-1](https://user-images.githubusercontent.com/1640233/28111892-bb2164f6-66ff-11e7-847e-e1808e101d79.png)

**Comment by Blendify** [comment]
This is not a bug in the theme because `:math:` is adding a space to the equation. I would move the period into `:math:` and/or report the issue to the particular math extension you are using.

**Comment by kassbohm** [comment]
thanks.
