### ISSUE TITLE
Footnotes have excessive margins

### ISSUE THREAD

**Issue by adrian5** [rtfd/sphinx_rtd_theme#440]
I don't know if I'm doing something wrong with my markup, but footnotes have very large spacing compared to their size.

```rst
6. **remote:** Remove old key from ``~/.ssh/authorized_keys``.
7. **client:** Delete old key files.

.. [1] https://wiki.mozilla.org/Security/Guidelines/OpenSSH#OpenSSH_client
.. [2] https://wiki.mozilla.org/Security/Guidelines/OpenSSH#OpenSSH_server
```

Produces

```html
  …
  <li><strong>remote:</strong> Remove old key from <code class="docutils literal"><span class="pre">~/.ssh/authorized_keys</span></code>.</li>
  <li><strong>client:</strong> Delete old key files.</li>
</ol>
<div class="wy-table-responsive">
  <table class="docutils footnote" frame="void" id="id3" rules="none">
  …
  </table>
</div>
<div class="wy-table-responsive">
  <table class="docutils footnote" frame="void" id="id4" rules="none">
  …
  </table>
</div>
```
Which under **sphinx-rtd-theme** looks like this:

![footnotes](https://user-images.githubusercontent.com/5426924/28244022-c1a3da8e-69de-11e7-92ee-834ecdaa582a.png)

**Comment by rwenz3l** [comment]
Ran into the same issue today and could 'quick-fix' it by removing/(wrap comments around)

```margin-bottom: 24px;```.

of the css class

```.wy-table-responsive```

I'm pretty sure this is not the best way of handling this so it would be great if any of the devs could chime in and do a proper fix.

**Comment by adrian5** [comment]
Yes, thanks. I'm not sure if other elements might be affected by this though (not that I saw any), as the developers probably have their reasons for this margin. I hope they give this a second look, as I understand too little of the theme to justify submitting a pull request.

**Comment by jessetan** [comment]
I think the problem is that each footnote (same for citations) is turned into a table with a single row, instead of a table with multiple rows. Since this is done by docutils, it can not be easily changed from Sphinx or the html theme.
Each table is wrapped in a div to make it responsive, which has a non-zero `margin-bottom`, which is the cause of this spacing.
I have a possible workaround, will file a PR
