### ISSUE TITLE
Better JavaScript syntax highlighting

### ISSUE THREAD

**Issue by TimKam** [rtfd/sphinx_rtd_theme#441]
The Sphinx Read the Docs theme could do better in highlighting JavaScript code:
![js_syntax_highlighting](https://user-images.githubusercontent.com/5434565/28287477-23a1d1e2-6b3c-11e7-84d3-3398c35036ad.png)

Sphinx/Pygments already provides the necessary classes:
![classes_highlight](https://user-images.githubusercontent.com/5434565/28287530-5189e522-6b3c-11e7-92f8-f96b6d11ecf2.png)

So this should be merely a matter of adding additional styles.

If this makes sense to you, I could try to find the time for creating a PR.

**Comment by Blendify** [comment]
PRs are welcome anytime.

**Comment by ericholscher** [comment]
Yep, this would be a great addition!

**Comment by ItsPugle** [comment]
@TimKam What Atom UI/Syntax do you use?

**Comment by Blendify** [comment]
https://github.com/rtfd/sphinx_rtd_theme/pull/448 should fix this.

**Comment by skaller** [comment]
Could I have some feedback on this please? In my case, it isn't JS that's the problem, but other Pygments lexers. With "classic" html_theme the colours are strong, the bolding good, and the sizes slightly bigger, and the background different from RTD. I don't mind the size change or background difference much, but the Pygments colours are basically clobbered.

The bolding is unnoticeable and almost all the colour is bled away, except the disgusting bright red used for string literals.

This is running the online version of RTD. Shouldn't the theme respect the Pygments colours?

The problem I have is that the tokenisation scheme used doesn't really fit my language or what I want to see, so I have to fudge a bit to get the appearance right, but nothing works on RTD. 

My language (Felix) isn't the only one impacted. C++ code is similarly impacted. Comments get faded to almost unreadable status, colour is bled away.

**Comment by Blendify** [comment]
The reason this does not work is that the HTML is not aware of the Pygments CSS #448 was going to fix this but this change is now included in a larger set of changes that can be found in this PR: #467. There are two temp fixes:

1. Use `pip install git+https://github.com/rtfd/sphinx_rtd_theme.git@6da7eb974754582353e80eada1151751745e185c`

2. Add `http://www.sphinx-doc.org/en/stable/extdev/appapi.html#sphinx.application.Sphinx.add_stylesheet` to the conf.py to link the css file manually.

**Comment by skaller** [comment]
Ok thanks!

actually I used a a <style> tag in a _template/layout.html and that seemed to work. The template gets injected after the main css is linked so it overrides it.

**Comment by Blendify** [comment]
Basic support for this has been added and #504 finishes this up. Closing.
