### ISSUE TITLE
Nested menu items are barely readable

### ISSUE THREAD

**Issue by Nazg-Gul** [rtfd/sphinx_rtd_theme#453]
Using gray text on gray background is bad idea, especially if one darkens the background with higher nested levels. Here is an example:

  https://docs.blender.org/manual/en/dev/render/cycles/settings/scene/render/index.html

"Object Settings" is nearly unreadable there.

**Comment by jessetan** [comment]
Closing, this is fixed by #638. Please reopen if you disagree.
