### ISSUE TITLE
Remove Monaco font family altogether?

### ISSUE THREAD

**Issue by unthingable** [rtfd/sphinx_rtd_theme#460]
As many reporters of a similar problem have stated back in 2014, I am no font expert. Still, from my limited research it seems Monaco has no business being in the list of families for monospaced things, seeing that it has no bold variant and is not easily removable on MacOS Sierra. Chrome appears to have fixed this internally but Safari has not:

<img width="202" alt="untitled" src="https://user-images.githubusercontent.com/925755/30326963-a307ee2a-97ca-11e7-9010-fdf9291c62a2.png">

(as seen on http://docs.idris-lang.org/en/latest/st/state.html)

**Comment by Blendify** [comment]
Considering this is not even our main monospace font but a fallback for a couple of fallbacks I have no problem removing it. But would like to hear from @agjohnson and @ericholscher first.
