### ISSUE TITLE
How do I consistently add an extra CSS file to override the existing stylesheets

### ISSUE THREAD

**Issue by vharsh** [rtfd/sphinx_rtd_theme#474]
I tried overriding the default colour of the ReadTheDocs theme.
I saw different results

#### CSS files seen locally
- "_static/css/theme.css"
- "_static/theme_overrides.css"

#### CSS files seen on ReadTheDocs
- "_static/theme_overrides.css"
Please suggest a consistent way so that I can add a custom CSS, which is applied **both** locally & and online.

**Comment by Blendify** [comment]
Have a look at http://www.sphinx-doc.org/en/stable/extdev/appapi.html#sphinx.application.Sphinx.add_stylesheet

**Comment by kiwiroy** [comment]
The `set css_files` from [this post](http://tinkerer.me/doc/theming.html#add-a-custom-stylesheet) on theme modification worked, although adding `@import url("//media.readthedocs.org/css/sphinx_rtd_theme.css");` to the top of `_static/theme_overrides.css` also appeared functional.
