### ISSUE TITLE
Google analytics still broken?

### ISSUE THREAD

**Issue by vatsan** [rtfd/sphinx_rtd_theme#477]
I am using RTD with Sphinx to host my page on GitHub pages. I am trying to track web traffic to my page with Google Analytics. We're using an enterprise version of GitHub, so we don't have the setting to specify Google Analytics ID directly in the GitHub pages. I've searched all around, while Sphinx documentation indicates we can create a custom "analytics.html" template that extends "layout.html" and plug in the Google Analytics script in there, this does not work with RTD.

The README.md file also indicates that we can specify the value for "analytics_id" in the dict "html_theme_options" in file conf.py, but this again does not seem to be getting picked up when I generate my docs. I cannot host my docs on readthedocs.org, I can only host it on GitHub pages (behind an internal firewall). How do i plug in Google Analytics tracker for my project? I want this setting to be picked up during the document generation process itself.

I found a bunch of old tickets from 2014 on this matter, it is unclear if there was a proper resolution. I'd appreciate any pointers.

**Comment by Blendify** [comment]
This is currently not supported by the theme and we are waiting on #411 in the meantime you can use either https://pypi.python.org/pypi/sphinxcontrib-googleanalytics/ or the http://docs.readthedocs.io/en/latest/guides/google-analytics.html feature on RTD docs

**Comment by vatsan** [comment]
Thanks for responding. sphinxcontrib-googleanalytics hasn't been updated in 7-8 years and the second link works only for docs hosted on RTD.

I found a better solution in this Stackoverflow suggestion. It works alright with RTD, I am now able to use Google Analytics on Sphinx generated RTD themed docs hosted on GitHub.

https://stackoverflow.com/a/41885884

Here's how my snippet looks like in my conf.py
_________
def setup(app):
    """Insert Google Analytics tracker
       Based on this Stackoverflow suggestion: https://stackoverflow.com/a/41885884
    """
    app.add_javascript("https://www.googletagmanager.com/gtag/js?id=UA-XXXXXXX")
    app.add_javascript("google_analytics_tracker.js")
_________

I placed the following in _static/google_analytics_tracker.js:
_________
window.dataLayer = window.dataLayer || [];
function gtag(){dataLayer.push(arguments);}
gtag('js', new Date());
gtag('config', 'UA-XXXXXX');
_________

**Comment by Blendify** [comment]
Closing this as it is more of a question/feature request than a bug.
