### ISSUE TITLE
theme.css.map not found in web server

### ISSUE THREAD

**Issue by tedzhu** [rtfd/sphinx_rtd_theme#478]
https://github.com/rtfd/sphinx_rtd_theme/blob/9d704f287ac197dfb1c9b27f0acfb91267dce4f1/setup.py#L26

Should this include all files under css/ instead of only the .css files?

**Comment by Blendify** [comment]
I think that the .map file should only be for developers. But maybe end users want this to be able to override the theme? I have done many custom mods to the theme for projects and never needed it.

**Comment by tedzhu** [comment]
Currently the web server will complain that the .map file couldn't be found, the noise is kind of sub optimal.  
 Agreed it might not be interesting to end users. Maybe remove the reference to it in the build?
