### ISSUE TITLE
Too wide intervals between links in the references section of the docstrings

### ISSUE THREAD

**Issue by skirpichev** [rtfd/sphinx_rtd_theme#479]
References section formatted as per [numpydoc standard](https://github.com/numpy/numpy/blob/master/doc/HOWTO_DOCUMENT.rst.txt#sections).
[Here](http://diofant.readthedocs.io/en/v0.8.0/modules/series.html#diofant.series.residues.residue) is an example:
![1](https://user-images.githubusercontent.com/2155800/32393035-131d0aaa-c0e9-11e7-8ebe-29b2aae3bc84.png)

**Comment by Blendify** [comment]
Fixed in #488
