### ISSUE TITLE
Disabled collapse_navigation stops working when sticky_navigation is also disabled

### ISSUE THREAD

**Issue by rosatamsen** [rtfd/sphinx_rtd_theme#481]
How come these two settings don't work when both are set to false?
```
html_theme_options = {
     'collapse_navigation': False,
     'sticky_navigation': False,
}
```
`'collapse_navigation': False` and `'sticky_navigation': True` allows the user to collapse/expand all items in the sidebar. Which is what I want.

However, I do not want the sticky nav bar. But when I set `'sticky_navigation': False`, all the little + signs that allow the user to collapse/expand items simply go away as if `'collapse_navigation'` was set to True.

Is there a way to have collapsible navigation items without a sticky nav bar?

**Comment by jessetan** [comment]
This is not working because the navigation JS code is only activated when sticky nav is enabled. If sticky nav is disabled, the toggles to expand navigation are not added.
PR #519 should fix this.
