### ISSUE TITLE
Text decoration for abbreviations/acronyms

### ISSUE THREAD

**Issue by hagenw** [rtfd/sphinx_rtd_theme#482]
You can define an acronym in sphinx with
<pre>
:abbr:`WFS (Wave Field Synthesis)`
</pre>
This will be converted to
```html
<abbr title="Wave Field Synthesis">WFS</abbr>
```
in HTML.
The abbreviation is highlighted by a dotted border below the word. In addition, newer browsers add automatically an underline to it. The final result looks then like this:
![abbr](https://user-images.githubusercontent.com/173624/32885559-bf9449c6-cab5-11e7-8ea4-a3fc2f4f8013.png)
Which is not the intended result, I guess.

There would be two ways of removing one of those lines:
1.) Don't add the dotted bottom line. But then it will only have a text decoration in newer browsers.
2.) Suppress the browser text decoration with CSS:
```css
abbr[title] {
    border-bottom: 1px dotted;
    text-decoration: none !important;
}
```
This would result in:
![abbr_fixed](https://user-images.githubusercontent.com/173624/32885653-0414d840-cab6-11e7-92d5-adb2443f401f.png)

**Comment by Blendify** [comment]
Thanks for looking into this and figuring out the problem, I always thought this looked a little funny. @agjohnson @ericholscher is you guys do not have another opinion I prefer the idea of suppressing the text-decoration.

**Comment by ericholscher** [comment]
Seems like the later option is the best, but not sure about unintended outcomes, but if it's scoped to `abbr` it seems good.

**Comment by agjohnson** [comment]
I hit this the other day. `border-bottom: 1px` is what i'd prefer, so i think this fix is fine. The fix should avoid `!important` though.

**Comment by hagenw** [comment]
I agree, it works also without `!important`.
