### ISSUE TITLE
Admonitions

### ISSUE THREAD

**Issue by nowox** [rtfd/sphinx_rtd_theme#538]
On this page we can see that custom admonitions have not the same format than other admonitions. It is wider and without background of the body text.

https://sphinx-rtd-theme.readthedocs.io/en/latest/demo/demo.html#admonitions

How can I fix this?

**Comment by Blendify** [comment]
If I remember correctly this is fixed in master and we just need to release
an update.

**Comment by Blendify** [comment]
Yes, this was fixed by d24f7ca6b57052eaf0843d56da46e1bfc71aa7f5 please either use the current release beta or wait for the next official release.
