### ISSUE TITLE
Line numbers do not line up with code

### ISSUE THREAD

**Issue by wallw-bits** [rtfd/sphinx_rtd_theme#547]
The `<pre>` tag produced by `code-block` or `literalinclude` has `line-height: normal` while the `<pre>` tag displaying the line numbers uses `line-height: 1.5`.

Relevant CSS blocks according to Chrome:
```
.rst-content .highlight>pre {
    line-height: normal;
}

div[class^='highlight'] pre {
    white-space: pre;
    margin: 0;
    padding: 12px 12px;
    font-family: ...
    font-size: 12px;
    line-height: 1.5;
    display: block;
    overflow: auto;
    color: #404040;
}
```

**Comment by Blendify** [comment]
This has been fixed in master and will be included in the next release.
