### ISSUE TITLE
How to change the blue background color?

### ISSUE THREAD

**Issue by nowox** [rtfd/sphinx_rtd_theme#565]
### Problem

I am trying to change the blue background color. So I cloned the project and started to replace the `#2980B9` with something else, but it doesn't work because the color is generated from the sass theme. 

So I tried to replace all the `$blue` with `$red` into `_theme_variables.sass`. That background color is still coming from somewhere. 

### Reproducible Project

```rst
$ git clone https://github.com/rtfd/sphinx_rtd_theme.git
$ cd sphinx_rtd_theme
$ sed -i s/blue/red sass/*
$ grunt
$ grep -hor 2980B9 **/*.css | wc -w
38 # This 2980B9 is coming from somewhere... Where...

```

### Additional details

It seems nothing has changed on the theme when I modify the sass. I have tried to change the icon on the admonitions: 

```
diff --git a/sass/_theme_rst.sass b/sass/_theme_rst.sass
index 40cb58a..5252029 100644
--- a/sass/_theme_rst.sass
+++ b/sass/_theme_rst.sass
@@ -93,7 +93,7 @@
   .admonition-title
     @extend .wy-alert-title
     @extend .fa
-    @extend .fa-exclamation-circle
+    @extend .fa-book
```

When I save the file, grunt automatically refresh the theme, but I cannot see any change on `http://localhost:1919/demo/demo.html?highlight=admonition#admonitions`

Why?

**Comment by stevepiercy** [comment]
See #222

**Comment by nowox** [comment]
@stevepiercy not really useful. I notice the same issue as #222, but there is no real solution given

**Comment by nowox** [comment]
Solution in #567
