### ISSUE TITLE
:ref: target not highlighted in navigation bar

### ISSUE THREAD

**Issue by zprd** [rtfd/sphinx_rtd_theme#583]
here is an issue that should've been reported here, as discussed in:
https://github.com/rtfd/readthedocs.org/issues/3679

**my original description:**

here is an example of a link to a labeled section:
https://docs.readthedocs.io/en/latest/getting_started.html#in-rst

the navigation tree is not highlight correctly,
but the following link highlights 'in-markdown' section as expected:
https://docs.readthedocs.io/en/latest/getting_started.html#in-markdown

these two urls are the results of navigation, by clicking the two links in 'Write Your Docs' section
https://docs.readthedocs.io/en/latest/getting_started.html#write-your-docs

notice that 'in-markdown' label and title are approximately the same, and in-rst and 'in restructuredtext' aren't very close.

maybe a sphinx-doc issue but rtd is the only theme I know that highlights navigation tree, so the mistake might be more obvious here.

**Comment by zprd** [comment]
reproduced with master

**Comment by davidfischer** [comment]
I believe this is due to the following JavaScript which handles it:
https://github.com/rtfd/sphinx_rtd_theme/blob/0bc0969/js/theme.js#L115-L151

I think the easiest solution is to make sure the link anchor name matches.
