### ISSUE TITLE
I am trying to use RTD. my docs are in .md.  toctree does not work. ..toctree:: shows up on my page first page as text.  

### ISSUE THREAD

**Issue by azzyghiasvand** [rtfd/sphinx_rtd_theme#588]
### Problem

Contents:

.. toctree:: :maxdepth: 2

release information installation administration integration

.. only:: html

Indices and Tables

:ref:genindex
:ref:modindex
:ref:search

shows up rather than TOC.  
### Reproducible Project

Please give a link to a public reproducible project or provide an example of the Restructured Text that gives an issue.

```rst
Place RST code here (if any).
```

#### Error Logs/Results

1. WARNING: document isn't included in any toctree
I have tried every possible way that I have found on stack flow or other places, it does not work
I have modified my index.md so many times but it still cannot find these files.  there are there.
2. WARNING: Could not lex literal_block as "xml". Highlighting skipped.
      Don't know how to fix it.
3. When I do search, it searches for the text like "Control F? and does not bring up the right page.  It used to do that right.  Not sure what happened.
4. Every page is brought up 2 or 3 times - pls see attached.
Place any images or error logs that might be able to help solve the issue here.

#### Expected Results

Please describe how this should work properly.

### Environment Info

- Python Version:
- Sphinx Version:
- RTD Theme Version:

**Comment by Blendify** [comment]
This sounds like something to be addressed on https://github.com/rtfd/readthedocs.org and not something to do with the theme. Please resubmit your report there, Thank you.
