### ISSUE TITLE
enable versions

### ISSUE THREAD

**Issue by 3nids** [rtfd/sphinx_rtd_theme#592]
### Problem

I would like to include the versions.html in the sidebar and could not succeed.

### Reproducible Project

I tried to add versions.html in ** for sidebars, this had no effect.

#### Error Logs/Results

Nothing

### Environment Info

- Python Version: 3.6
- Sphinx Version: 1.7.1
- RTD Theme Version: 0.2.4

**Comment by 3nids** [comment]
not sure this is really an issue or a questions, I posted this on [stackoverflow](https://stackoverflow.com/questions/49331914/enable-versions-in-sidebar-in-sphinx-read-the-docs-theme)

**Comment by Blendify** [comment]
Please see https://github.com/rtfd/sphinx_rtd_theme/pull/574
