### ISSUE TITLE
Highlighting in code-block is barely visible

### ISSUE THREAD

**Issue by ruslo** [rtfd/sphinx_rtd_theme#603]
### Problem

The result of `:emphasize-lines:` directive is barely visible inside `code-block` because background color and emphasize color have the same tone.

### Reproducible Project

An example of code:

```rst
.. code-block:: cpp
  :emphasize-lines: 3

  #include <iostream>

  int main() {
    std::cout << "Hello" << std::endl;
  }
```

#### Error Logs/Results

Rendered with 0.3.0 version of sphinx_rtd_theme:
![bad](https://user-images.githubusercontent.com/4346993/38404846-7b448752-3975-11e8-894e-295164e8a60c.png)

#### Expected Results

Rendered with 0.2.4 version of sphinx_rtd_theme:
![good](https://user-images.githubusercontent.com/4346993/38404724-c5cb4be0-3974-11e8-9947-4d382e082bb4.png)

### Environment Info

- Python Version: 2.7.12
- Sphinx Version: 1.4.5
- RTD Theme Version: 0.3.0

**Comment by jessetan** [comment]
I agree this is hard to read, but I don't think this is an issue with sphinx-rtd-theme. The color comes from Pygments. Try setting `pygments_style` to `default` or `monokai` and see how the colors change.
We could theoretically provide an override so the user can choose a color.

Another issue that can be seen from the above screenshots is that the highlight doesn't span the entire line. That makes it less noticeable, especially for short lines.

**Comment by ruslo** [comment]
> I don't think this is an issue with sphinx-rtd-theme. The color comes from Pygments.

I've locked Pygments to `2.2.0` in requirements.txt for both 0.3.0 and 0.2.4 version of sphinx_rtd_theme.

> Try setting pygments_style to default or monokai and see how the colors change

Yes, `default` looks better, thanks.

> Another issue that can be seen from the above screenshots is that the highlight doesn't span the entire line. That makes it less noticeable, especially for short lines.

That's true, is it a sphinx_rtd_theme issue?

**Comment by jessetan** [comment]
>> I don't think this is an issue with sphinx-rtd-theme. The color comes from Pygments.
> 
> I've locked Pygments to 2.2.0 in requirements.txt for both 0.3.0 and 0.2.4 version of sphinx_rtd_theme.

I meant that Pygments defines both the highlight color and the background color for each theme. In 0.2.4 this was not used, in 0.3.0 it is.

A possible workaround for this is to add a new theme option that overrides the highlight color set by Pygments (with class `.hll`), but I still think we should just take whatever Pygments gives us. Alternatively, you could supply your own custom CSS.
@Blendify as you've worked on fixing Pygments support, how do you feel about this?

>> Another issue that can be seen from the above screenshots is that the highlight doesn't span the entire line. That makes it less noticeable, especially for short lines.
> 
> That's true, is it a sphinx_rtd_theme issue?

Yes, but a separate one.

**Comment by Blendify** [comment]
> but I still think we should just take whatever Pygments gives us

I agree. But also to go along with your report it looks like you are overriding the theme default and using the sphinx pygment theme instead. So, check your conf.py for this. The default theme matches 0.2.4 much closer.

Because we just what pygments give us there is not really a bug in the theme anymore so closing this issue.
