### ISSUE TITLE
Version 0.3.0 breaks sidebar

### ISSUE THREAD

**Issue by goerz** [rtfd/sphinx_rtd_theme#610]
See https://github.com/rtfd/readthedocs.org/issues/3925

**Comment by jessetan** [comment]
See my comment in https://github.com/rtfd/readthedocs.org/issues/3925#issuecomment-381408874, I think this is not caused by the theme but by the way it is packaged on RTD.
Leaving this issue open until we have confirmation on this though.

**Comment by Blendify** [comment]
I can confirm on http://shenfun.readthedocs.io/en/latest/

@jessetan I think this might be from https://github.com/rtfd/sphinx_rtd_theme/commit/5db94ebf5f6f06d36fb961a7cee0b53d426214b6?

**Comment by jessetan** [comment]
@Blendify yes. The code in layout.html should match the code in theme.js. That is not the case in rtfd/readthedocs.org#3925.
