### ISSUE TITLE
adding tests to tar-ball on pypi

### ISSUE THREAD

**Issue by arunpersaud** [rtfd/sphinx_rtd_theme#620]
Would it be possible to include the tests in the tarball? This would be helpful for example for linux distributions that package this module to make sure that everything works before publishing the package (e.g. opensuse automatically runs tests for packages if they are available before publishing a new rpm).

Thanks

Arun

**Comment by ericholscher** [comment]
Not sure what needs to happen. I believe we need to add additional metadata to our setup.py?

**Comment by arunpersaud** [comment]
sorry for the late reply. I'm not that familiar with it either, but I think you want to add a MANIFEST.in file where you can specify extra files that should go into sdist.

https://docs.python.org/3/distutils/sourcedist.html
