### ISSUE TITLE
Sticky nav does not work on fresh page load

### ISSUE THREAD

**Issue by begriffs** [rtfd/sphinx_rtd_theme#629]
### Problem

When you first arrive on a docs page, the navigation is not sticky, meaning the menu will scroll as you scroll the page.

### Reproducible Project

Visit the following page. On first load the nav will not be sticky.
https://docs.citusdata.com/en/v7.3/admin_guide/cluster_management.html#choosing-cluster-size

But try clicking another subsection of the currently open section in the table of contents. In fact click "Choosing Cluster Size" itself, and the nav will become sticky. 

#### Expected Results

The nav should be sticky when loading a new page, even if the navigation menu hasn't been clicked yet.

### Environment Info

- Sphinx Version: 1.5.0  (also fails on 1.7.4)
- RTD Theme Version: 0.2.4 (also fails on 1.3.1)

**Comment by jessetan** [comment]
When would you expect the navigation to be not sticky? If it is sticky when you load a doc page, it will always be sticky.

**Comment by begriffs** [comment]
> When would you expect the navigation to be not sticky?

Ideally it would be sticky at all times.

> If it is sticky when you load a doc page, it will always be sticky.

It's the other way around: it's *not* sticky when I first load a doc page. It only becomes so after I click a item in the table of contents which jumps to an `#anchor_name` in the URL.

**Comment by jessetan** [comment]
In the theme "sticky" actually means that the navigation sticks to the content and moves with it, rather than staying still as the content is scrolled (as you described)
Have you tried truning sticky nav off in `conf.py`:
``` py
html_theme_options = {
    'sticky_navigation': False
}
```

**Comment by begriffs** [comment]
I see. That's somewhat surprising since "sticky menu" or "sticky position" typically means the opposite when people talk about page styling.

Anyway, I tried setting the property to False, which had no effect as you suspected. So we'll just wait for a 0.3 version and try again. Thanks for debugging and opening a pull request for it.
