### ISSUE TITLE
static folders are empty

### ISSUE THREAD

**Issue by yoong93** [rtfd/sphinx_rtd_theme#637]
### Problem

Give details on your issue.

After I specified the theme in conf.py and run make html, html file is successfully created but error occurs. I think the problem is css / fonts / js folders are all being empty -- after I manually moved from the git source, it works again. Is this the way how things originally works? 
Also, after I moved these files, there is one more error remaining -- says "Uncaught ReferenceError: module is not defined at theme.js:200" 

Thanks

**Comment by stsewd** [comment]
Please provide your project and build url
