### ISSUE TITLE
Sphinx RTD Theme embed in a nested div

### ISSUE THREAD

**Issue by fahadm** [rtfd/sphinx_rtd_theme#644]
### Problem
Unable to embed read the docs sphinx_rtd theme in a page inside an element.
What I want to do is that I want the side navigation bar to be relative to the div it is currently in, rather than being absolute to window.

I am currently unable to see a way a to do this.

to give you a perspective what I want do is:

xx                                      Header
xx-----------------------------------------------------------------------------
                                        Content
margin|                             Embed SPHINXRTD          | margin
margin| nav bar -            Welcome to docs!                | margin
margin| nav bar -               content                              | margin
margin| nav bar -               content                              | margin

But when I try to embed it, what I get is this ( due to absolute positioning in the nav bar)

nav bar -                              Header
nav bar -----------------------------------------------------------------
nav bar -                           Content
nav bar - margin|           Embed SPHINXRTD          | margin
nav bar - margin|             Welcome to docs!                | margin
nav bar - margin|                content                              | margin
nav bar - margin|                content                              | margin

And it ends up looking weirder if I try to change the css.

I hope I am not asknig in the wrong place.

**Comment by davidfischer** [comment]
Do you have a link you can share that illustrates this problem? How are you embedding it?

**Comment by fahadm** [comment]
I don't have a link but here are pictures
This is what it looks like
![actual](https://user-images.githubusercontent.com/823401/40480435-d02de6ba-5f4e-11e8-83c0-7444981de17e.png)

This is how I want it to look like
![wanted](https://user-images.githubusercontent.com/823401/40480444-d7985d2c-5f4e-11e8-84bf-c7df56725fc0.png)


The way I am embedding it is by loading the html page dynamically (via jquery ) in a <div> inside my page.

**Comment by jessetan** [comment]
This is what `<iframe>` was invented for, why are you placing it in a `<div>`?

**Comment by fahadm** [comment]
Well the reason I am not using an Iframe is that, in an Iframe, you lose the ability to do direct links to different pages of the documentation, as the user can navigate away to a different part of the documentation.

**Comment by jessetan** [comment]
You can try to set `position: absolute` on `.wy-nav-side` to position it relative to the containing div rather than the window.
Since it will then scroll with the content (which you probably do not want) you can add `height: 100%` to `.wy-nav-content-wrap` and `overflow-y: scroll` to `.wy-nav-content`.

If that doesn't work for you, then maybe it's better to wait for #510 and build your own navigation.

**Comment by Blendify** [comment]
Closing due to no response and it is a duplicate.
