### ISSUE TITLE
Add a title to the note box, change box color?

### ISSUE THREAD

**Issue by tonyriverms** [rtfd/sphinx_rtd_theme#645]
I am not sure if this theme currently supports these features. I would like to  

1. add a title to the note box through the "note" directive

<img width="536" alt="capture" src="https://user-images.githubusercontent.com/9701455/40588965-9a9fed10-61b3-11e8-9550-a466a2ff3a1b.PNG">

2. change the color of the box through the "note" directive

Any way to achieve this?

**Comment by jessetan** [comment]
> 1. add a title to the note box through the "note" directive

This is a [limitation in reStucturedText](http://docutils.sourceforge.net/docs/ref/rst/directives.html#admonitions), so if you need this you can write a Sphinx extension that takes the caption as an argument or option.

> 2. change the color of the box through the "note" directive

Setting a color directly is not possible, but you can use the `:class:` option and add custom CSS that applies the desired color. This is also not unique to this theme, but rather the way Sphinx/rst works.
