### ISSUE TITLE
Code block line height causes lines to overlap

### ISSUE THREAD

**Issue by FernandoBasso** [rtfd/sphinx_rtd_theme#656]
### Problem

Lines appear to be not tall enough, and text lines overlap a little on Opera, Chromium, and Epiphany browsers.

#### Error Logs/Results

https://ruby-howto.readthedocs.io/en/latest/symbols.html

![sphinx_rtd_theme_bad_font_rendering_for_code_blocks](https://user-images.githubusercontent.com/6560620/42133390-a41632f2-7cff-11e8-9f5b-949938d9ba3c.png)

### Environment Info

Running Xubuntu 18:04.

The browsers mentioned are up to date.

- Python Version: 3.6.5 (from the ubuntu repos)
- Sphinx Version: python3-sphinx  1.6.7-1ubuntu1 (installed from the ubuntu repos).
- RTD Theme Version: 0.4.0 (installed through pip)

If I just change `line-height` from normal to `1.5`, for instance, then things look just fine.

Also note that the normal, non code text does't have the same problem. Only code blocks.

**Comment by jessetan** [comment]
This is caused by the small line height of Liberation Mono, none of the other fonts have this issue.

**Comment by FernandoBasso** [comment]
Okay. Thanks.
