### ISSUE TITLE
pdf generation using weasyprint get only single page

### ISSUE THREAD

**Issue by jacgeo** [rtfd/sphinx_rtd_theme#658]
### Problem

I created an HTML page using sphinx_rtd_theme and convert the HTML to PDF using weasyprint package, but PDF generated it's first page only. For other themes get all PDF pages when added the below css `'* { float: none !important; }' `. It was not working for sphinx_rtd_theme. 

### Environment Info

- Python Version:3.6
- Sphinx Version:1.8
- RTD Theme Version: 0.40
- WeasyPrint :  0.42.3

**Comment by davidfischer** [comment]
Which page were you generating a PDF from and how did you do it?

**Comment by Blendify** [comment]
Closing because there was no reply, if this was a mistake we can re-open.
