### ISSUE TITLE
Nicer styles for <kbd>

### ISSUE THREAD

**Issue by honzajavorek** [rtfd/sphinx_rtd_theme#669]
### Problem

Currently the `:kbd:` role, or more precisely the `<kbd>` HTML tag, renders like this:

<img width="128" alt="image" src="https://user-images.githubusercontent.com/283441/45642226-ee9f5100-bab7-11e8-917a-816160316956.png">

I think it would be nicer if the styles were closer to what GitHub does, so one could document keys to press or buttons to click with more visual aid:

<kbd>Download</kbd>

### Reproducible Project

Link: https://cojeapi.readthedocs.io/cs/latest/content/02-klient-server.html#klient-v-terminalu-curl (the "Windows" tab)

```rst
Click on :kbd:`Download`.
```

#### Expected Results

The role renders like something resembling a button or a computer key.

### Environment Info

- Python Version: not relevant
- Sphinx Version: not relevant
- RTD Theme Version: 0.4.0

**Comment by honzajavorek** [comment]
Great! If you need any help, let me know. I'm not great with contemporary CSS, but I guess this would be in my powers 😄

**Comment by stsewd** [comment]
Fixed in https://github.com/rtfd/sphinx_rtd_theme/pull/677
