### ISSUE TITLE
Search does not work

### ISSUE THREAD

**Issue by AndreyKiryliuk** [rtfd/sphinx_rtd_theme#673]
### Problem

Search does not work.

### Reproducible Project

there is no reference to a public project

```rst
Welcome to example documentation!
===================================

TODO
----

1. Step 1
2. Step 2
```

#### Expected Results

Search will work

### Environment Info

- Python Version: 2.7.15
- Sphinx Version: 1.8.1
- RTD Theme Version: 0.4.1

When I add 
<script type="text/javascript" id="documentation_options" data-url_root="./" src="_static/documentation_options.js"></script>
to build/search.html before <script type="text/javascript" src="_static/jquery.js"></script>
Search starts working.

**Comment by Blendify** [comment]
This was fixed in #672
