### ISSUE TITLE
Slow menu updates; should be able to browse the menu without loading the page

### ISSUE THREAD

**Issue by jfehrle** [rtfd/sphinx_rtd_theme#681]
### Problem

Example page (any page should do): https://coq.inria.fr/distrib/current/refman/language/gallina-specification-language.html

When browsing the left-hand menu, clicking on a new top-level section can be slow (a couple seconds) because it loads the full document.  This is a long while just to see a few subentries in the menu. The user should be able to browse the menu without so much delay.

For example: I'm looking at the "Gallina specification language" chapter. I want to see the subentries of "Extensions of Gallina" in the short (on-screen) table of contents. Clicking on "Extensions of Gallina" takes a couple seconds before its subentries are visible because that loads the entire chapter as well.

![image](https://user-images.githubusercontent.com/1253341/46371716-faede700-c63d-11e8-9aa6-f63a65a95246.png)

![image](https://user-images.githubusercontent.com/1253341/46371756-122cd480-c63e-11e8-8037-33c524d064d1.png)

### Environment Info

- Python Version: 3.6.5
- Sphinx Version: 1.7.7
- RTD Theme Version: not sure but recent

Hope this is enough info and that this is the right project.  I'm not the one who set up Sphinx and RTD, I'm just updating documentation today.

**Comment by jessetan** [comment]
Try setting `collapse_navigation` to `False`. In your conf.py:
```py
html_theme_options = {
    'collapse_navigation': False
}
```

**Comment by jfehrle** [comment]
Perfect, thanks!
