### ISSUE TITLE
Local Table of Contents not formatted

### ISSUE THREAD

**Issue by hagopboz** [rtfd/sphinx_rtd_theme#685]
### Problem

When you use the contents directive to create a local table of contents, the table just formats as a list with no style. (no indents or bullets)

### Reproducible Project

https://onap.readthedocs.io/en/latest/submodules/vnfrqts/guidelines.git/docs/vnf_guidelines/vnf_guidelines.html

RST code:

.. contents::
   :depth: 3

#### Error Logs/Results

![image](https://user-images.githubusercontent.com/6490403/46637777-92f24180-cb12-11e8-8280-0d38fa40b0c3.png)

#### Expected Results

![image](https://user-images.githubusercontent.com/6490403/46637807-ac938900-cb12-11e8-8d4c-4ff1dd904d30.png)

### Environment Info

- Python Version: latest
- Sphinx Version: latest
- RTD Theme Version: latest

**Comment by jessetan** [comment]
@hagopboz Is this still an issue? The reproducible project is no longer accessible.

**Comment by Blendify** [comment]
Closing due to no response.
