### ISSUE TITLE
Subdivide master toctree

### ISSUE THREAD

**Issue by mmabey** [rtfd/sphinx_rtd_theme#699]
### Problem

I would really like to limit the `toctree` for certain subfolders to show only the page titles from that folder. I've searched through the docs for the RTD theme, Sphinx, and reStructuredText and can't find a way to do this with the existing feature set.

### Reproducible Project

The project I'm attempting this for is my personal website ([repo here](https://github.com/mmabey/mmabey.github.io)).

#### Expected Results

I'm adding pages to my website related to a class I'm teaching in a couple months, and I would like the left-hand menu to only show links for the class. In other words, the menu on the pages in the root folder would include a link to `cse469s19/index`, but the menu for all the pages in the `cse469s19` folder would only show the contents of the `toctree` directive in `cse469s19/index.rst`.

It would be pretty sweet if a solution would look something like specifying multiple values for the [`master_doc`](http://www.sphinx-doc.org/en/stable/usage/configuration.html#confval-master_doc) configuration variable, where [my current configuration](https://github.com/mmabey/mmabey.github.io/blob/src/conf.py#L56) would be changed to this:

```python
master_doc = ['index', 'cse469s19/index']
```

I know the feature I'm requesting is a bit unusual and may not be useful to very many people, so I understand if there isn't enough interest to gain traction. But if what I'm asking for is possible and someone can point me in the right direction to get started, that might be enough for me to implement it myself and submit a PR.

### Environment Info

- Python Version: 3.5.3
- Sphinx Version: 1.8.1
- RTD Theme Version: 0.4.2

**Comment by Blendify** [comment]
This is nothing we can do. Sphinx just gives us the tool to create a toc on a global (every document) or local (the current HTML page) level. You could maybe frankenstein two projects by combining there builds and the toctree allows external links:

```
.. toctree::

   Title <http://LINK>
````

This is not something we can do so I'm going to close this report.

**Comment by Blendify** [comment]
Sorry for the slow reply

**Comment by mmabey** [comment]
No worries. Thanks for taking the time to look into this!
