### ISSUE TITLE
Admonitions occupy 100% of screen size even when right aligned with images

### ISSUE THREAD

**Issue by colombojrj** [rtfd/sphinx_rtd_theme#702]
### Problem

Admonitions occupy 100% of screen size even when right aligned with images. interestingly sidebars work ok.

### Reproducible Project

```rst

.. image:: figs/EDOs_Eqs_Algebricas.svg
   :width: 400px
   :align: center
   :class: align-left

Blablablalba

.. note::

   blablabla
```

#### Error Logs/Results

Place any images or error logs that might be able to help solve the issue here.
![image](https://user-images.githubusercontent.com/3207971/49748984-4a7c0f00-fc8e-11e8-86a5-87418b69b45e.png)

#### Expected Results

The admonition should not occupy 100% of screen size in this case.

**Comment by Blendify** [comment]
Fixed by https://github.com/rtfd/sphinx_rtd_theme/pull/723
