### ISSUE TITLE
git shows unstaged files after clone

### ISSUE THREAD

**Issue by FranzForstmayr** [rtfd/sphinx_rtd_theme#708]
### Problem

My fresh install git shows unstaged files directly after cloning this repository.

#### Error Logs/Results

    `xxxx~/Workspaces/python$ git clone https://github.com/rtfd/sphinx_rtd_theme.git
    Cloning into 'sphinx_rtd_theme'...
    remote: Enumerating objects: 5, done.
    remote: Counting objects: 100% (5/5), done. 
    remote: Compressing objects: 100% (5/5), done.
    remote: Total 4566 (delta 0), reused 0 (delta 0), pack-reused 4561 
    Receiving objects: 100% (4566/4566), 10.42 MiB | 1.72 MiB/s, done. 
    Resolving deltas: 100% (2751/2751), done.
    xxxx:~/Workspaces/python$ cd sphinx_rtd_theme/ 
    xxxx:~/Workspaces/python/sphinx_rtd_theme$ git status
    On branch master
    Your branch is up to date with 'origin/master'.

    Changes not staged for commit:
      (use "git add <file>..." to update what will be committed)
      (use "git checkout -- <file>..." to discard changes in working directory)

	    modified:   docs/make.bat

    no changes added to commit (use "git add" and/or "git commit -a")
    xxxx:~/Workspaces/python/sphinx_rtd_theme$ git config -l
    core.repositoryformatversion=0
    core.filemode=true
    core.bare=false
    core.logallrefupdates=true
    remote.origin.url=https://github.com/rtfd/sphinx_rtd_theme.git
    remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
    branch.master.remote=origin
    branch.master.merge=refs/heads/master
    xxxx:~/Workspaces/python/sphinx_rtd_theme$ 
    `

#### Expected Results

Why is there a unstaged file? Am i missing some configuration

### Environment Info

- git version 2.17.1

**Comment by davidfischer** [comment]
I'm seeing this as well. It definitely has to do with CRLF settings. I'm investigating.

**Comment by catrina4200** [comment]
> ### Problem
> My fresh install git shows unstaged files directly after cloning this repository.
> 
> #### Error Logs/Results
> ```
> `xxxx~/Workspaces/python$ git clone https://github.com/rtfd/sphinx_rtd_theme.git
> Cloning into 'sphinx_rtd_theme'...
> remote: Enumerating objects: 5, done.
> remote: Counting objects: 100% (5/5), done. 
> remote: Compressing objects: 100% (5/5), done.
> remote: Total 4566 (delta 0), reused 0 (delta 0), pack-reused 4561 
> Receiving objects: 100% (4566/4566), 10.42 MiB | 1.72 MiB/s, done. 
> Resolving deltas: 100% (2751/2751), done.
> xxxx:~/Workspaces/python$ cd sphinx_rtd_theme/ 
> xxxx:~/Workspaces/python/sphinx_rtd_theme$ git status
> On branch master
> Your branch is up to date with 'origin/master'.
> 
> Changes not staged for commit:
>   (use "git add <file>..." to update what will be committed)
>   (use "git checkout -- <file>..." to discard changes in working directory)
> 
>     modified:   docs/make.bat
> 
> no changes added to commit (use "git add" and/or "git commit -a")
> xxxx:~/Workspaces/python/sphinx_rtd_theme$ git config -l
> core.repositoryformatversion=0
> core.filemode=true
> core.bare=false
> core.logallrefupdates=true
> remote.origin.url=https://github.com/rtfd/sphinx_rtd_theme.git
> remote.origin.fetch=+refs/heads/*:refs/remotes/origin/*
> branch.master.remote=origin
> branch.master.merge=refs/heads/master
> xxxx:~/Workspaces/python/sphinx_rtd_theme$ 
> `
> ```
> 
> #### Expected Results
> Why is there a unstaged file? Am i missing some configuration
> 
> ### Environment Info
> * git version 2.17.1

https://github.com/readthedocs/sphinx_rtd_theme/issues/708#issue-392173477

**Comment by bubthegreat** [comment]
Just a possibility worht looking into here - we work in a linux/windows shop, and we committed files in windows - but git clone by default will create files with OS line endings depending on settings - it's entirely possible this is expected behavior if the local config of the developer enforces one kind of line endings vs. another and you have developers with conflicting settings that are both committing files from different operating systems.

VSCode/Editor settings can be applied and git config settings can be applied to enforce consistent line endings on commit.

Ours are a combination of Mac OS, WSL Ubuntu, and windows 10 and I'm %9000 sure that I personally have been the cause of this at least once.
