### ISSUE TITLE
.admonition block elements close to floating elements

### ISSUE THREAD

**Issue by benjaoming** [rtfd/sphinx_rtd_theme#722]
### Problem

I think the CSS class `.admonition` shouldn't generally allow floats around it.

It looks like this:

![image](https://user-images.githubusercontent.com/374612/52915024-61169600-32cf-11e9-80f5-5c2cf40c8836.png)

Adding this style fixes it:

```
.admonition {
  clear: both;
}
```

![image](https://user-images.githubusercontent.com/374612/52915056-b357b700-32cf-11e9-854e-50d33e02d842.png)

### Reproducible Project

Put an image that floats, the example here:

```
.. figure:: /img/rpi_kit.jpeg
    :alt: Raspberry Pi and accessories
    :align: right
    :figwidth: 50%
```

#### Error Logs/Results

n/a

#### Expected Results

n/a

### Environment Info

- Python Version: 3
- Sphinx Version: 0.4.0
- RTD Theme Version:

**Comment by Blendify** [comment]
Fixed
