### ISSUE TITLE
Using deprecated Sphinx method - Please use app.add_js_file() instead.l

### ISSUE THREAD

**Issue by terrisgit** [rtfd/sphinx_rtd_theme#725]
See https://github.com/sphinx-doc/sphinx/issues/6088#issuecomment-466239708

**Comment by tk0miya** [comment]
I think this is the point of problem.
https://github.com/rtfd/sphinx_rtd_theme/blob/ecbc09f22a076b6ca985f6c5cab0967976dad12a/sphinx_rtd_theme/search.html#L12
