### ISSUE TITLE
Build failed without any reason

### ISSUE THREAD

**Issue by EDI-N** [rtfd/sphinx_rtd_theme#740]
### Build failed without any reason

Every RTD projects worked ok and yesterday without any **changes_what_can_provide_"fail"** I got **Build fail**. A lot of time I try to fix text/config.... nothing helped, so I think: "ok, happend" and clone wittingly good code from 
https://readthedocs.org/projects/edi-n/
to
https://readthedocs.org/projects/for-test/ and got **Build failed**

### Reproducible Project
projects with errors:
https://readthedocs.org/projects/for-test/
&
https://readthedocs.org/projects/icona/

#### Error Logs/Results

https://readthedocs.org/projects/for-test/builds/8834547/

#### Expected Results

Build completed

### Environment Info

- Python Version: 2.x
- Sphinx Version:
- RTD Theme Version:

**Comment by davidfischer** [comment]
This issue doesn't seem to be related to the Read the Docs theme per se, but it is a build error on RTD.

This looks like a unicode issue with LaTeX. It could possibly be related to https://github.com/rtfd/readthedocs.org/pull/5437 but I don't exactly see how.

**Comment by EDI-N** [comment]
Thank you, sory for wrong relation to "Read the Docs theme" group. I will copy my text from this issue and create new one to "readthedocs.org" group.
