### ISSUE TITLE
needtable not shown in RTD

### ISSUE THREAD

**Issue by 2Eagle2** [rtfd/sphinx_rtd_theme#767]
## Details

When running the basic example in Sphinx from https://sphinxcontrib-needs.readthedocs.io/en/latest/index.html#

database style table is not shown when using RTD

## Minimal Example:

.. req:: My first requirement
  requirement 1

.. req:: My second requirement
  requirement 2

.. needtable::
  :style: datatables

## Expected Result

the table is shown as in example

## Actual Result

only control panels of database is shown but not actual table

**Comment by stsewd** [comment]
Thank you, I'm moving this issue to the rtd theme repo

**Comment by jessetan** [comment]
This is not a theme issue, but an issue of the sphinxcontrib-needs extension. It uses floating elements that move `div.wy-table-responsive` out of view.
Unfortunately this theme can not accommodate all Sphinx extensions that exist. I suggest opening an issue at https://github.com/useblocks/sphinxcontrib-needs, perhaps they have a nice way of solving it without needing custom CSS in your project.
