### ISSUE TITLE
Remove Table of content from front page

### ISSUE THREAD

**Issue by astrom-tom** [rtfd/sphinx_rtd_theme#768]
### Problem

Give details on your issue.

I would like the table of content not to be shown in the from page (while still shown in the side bar)

### Reproducible Project

```
.. toctree::
   :maxdepth: 1
 
   Home <self>
   master1
   master2
   master3
   master4

```

#### Error Logs/Results

None

#### Expected Results

Well I just want the table of content to disappear in the front page.
### Environment Info

- Python Version: 3.7.3
- Sphinx Version: 2.0.1
- RTD Theme Version: 0.4.3

**Comment by Blendify** [comment]
Use:

```
.. toctree::
   :maxdepth: 1
   :hidden:
 
   Home <self>
   master1
   master2
   master3
   master4
````

**Comment by astrom-tom** [comment]
Perfect!
