### ISSUE TITLE
Style versionchanged and versionadded directives

### ISSUE THREAD

**Issue by seanh** [rtfd/sphinx_rtd_theme#99]
See the _Changed in version 2.0_ at the top of this page: http://docs.ckan.org/en/latest/maintaining/authorization.html. That's [versionchanged directive](http://sphinx-doc.org/markup/para.html?highlight=versionchanged#directive-versionchanged):

```
.. versionchanged:: 2.0
   Previous versions of CKAN used a different authorization system.
```

but in this theme it just looks like a normal paragraph.

It would be nice to style these so that they pop out, like notes, warnings etc do because these directives are very important.

Same comment for [versionadded](http://sphinx-doc.org/markup/para.html?highlight=versionchanged#directive-versionadded)

**Comment by stof** [comment]
This would be great. Is there any plan to style these directives ?
